/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 * XChain Node - Validator Service
 *
 * Validator-mode onboarding for the xchain-hub. `validator init` generates
 * an Ed25519 signing key and writes the validator config that install/start
 * inject into the hub container so it runs as a full validator (P2P + PBFT +
 * capability staking) instead of a standalone config oracle.
 *
 * Files (under configDir/validator/):
 *   signing.key                 64-hex Ed25519 seed (mode 0600): SIGNING_PRIVKEY_HEX
 *   validator.json              P2P + oracle settings + enabled flag + pubkey
 *   hub-caps/capabilities.json  HUB_CAPABILITY_CONFIG: MIN_STAKE thresholds +
 *                               self-test blocks
 *   wallets.env                 the two coin wallets (mode 0600): the BTC stake
 *                               wallet (funds fees, mints and holds the STAKE)
 *                               and the DOGE publisher wallet (pays for price
 *                               rounds and anchors). Generated by init, or
 *                               imported from operator-supplied WIFs.
 *   signer/signer.js + .env     the HUB_SIGNER_MODULE the hub loads to sign
 *                               DOGE publishes. Mounted read-only into the
 *                               container; the WIF stays in this directory.
 *
 * Both wallets are ordinary single-key P2PKH wallets, so an operator who wants
 * a branded (vanity) address generates the key elsewhere and imports the WIF:
 * `--import-stake-key` / `--import-doge-key` prompt for it with echo off, and
 * XCHAIN_NODE_STAKE_WIF / XCHAIN_NODE_DOGE_WIF carry it non-interactively.
 * Never as an argv value: a WIF in argv is a WIF in every process listing.
 *
 * The hub's API key is deliberately NOT one of these. A hub refuses to boot
 * without HUB_API_KEY unless keyless operation is declared, so init mints one,
 * but it belongs to the HOST rather than to this validator identity: the local
 * indexer and the shared services authenticate to the same hub with the same
 * value. It therefore lives in the shared 0600 sidecar config/hub.local
 * alongside HUB_DB_PASS (ConfigService.ensureHubApiKey).
 *
 * Why capabilities.json sits in its own `hub-caps/` subdirectory rather than
 * beside the other two: the hub container mounts it, and a SINGLE-FILE bind
 * mount breaks `docker cp` against that container forever. Docker's copy path
 * recreates every mount destination as a directory, so it hits the existing
 * file and aborts the whole operation with
 * "mkdirat validator/capabilities.json: file exists" - for ANY path copied,
 * not just the mounted one. Mounting a DIRECTORY instead has no such problem.
 * The directory that gets mounted must therefore contain the capability config
 * and NOTHING else: mounting `validator/` itself would put signing.key, the
 * validator's private key, inside the hub container. ensureCapabilityConfigLayout()
 * migrates pre-hub-caps installs, and assertCapsDirIsolated() refuses to build
 * the mount if anything else ever lands in that directory.
 *
 * The private key is never logged. Only the PUBLIC key is printed (operators
 * stake to it).
 ********************************************************************/

const fs   = require('fs')
const path = require('path')
const crypto = require('crypto')
const { configDir } = require('../config/constants')
const { ensureHubApiKey } = require('./ConfigService')

const VALIDATOR_DIR   = path.join(configDir, 'validator')
// The stack ref this CLI tells an operator to install. xchain-node's own
// version IS the platform version, so deriving the hint here keeps it on the
// release the operator is actually holding, and it cannot rot the way a
// hardcoded ref does. It said `master` until 2026-09-01: an unpinned tracking
// install, contradicting every other instruction we give, printed at the exact
// moment a new validator is deciding what to run.
const RELEASE_REF = 'v' + require('../../package.json').version
const KEY_FILE        = path.join(VALIDATOR_DIR, 'signing.key')
const SETTINGS_FILE   = path.join(VALIDATOR_DIR, 'validator.json')

// The ONLY file allowed in CAPS_DIR: that whole directory is bind-mounted into
// the hub container (see the header comment), so anything else added here is
// handed to the hub too.
const CAPS_BASENAME   = 'capabilities.json'
const CAPS_DIR        = path.join(VALIDATOR_DIR, 'hub-caps')
const CAPS_FILE       = path.join(CAPS_DIR, CAPS_BASENAME)

// Where installs before the hub-caps split kept the same file. Migrated on
// first use; never mounted (it is the single-file mount that broke docker cp).
const LEGACY_CAPS_FILE = path.join(VALIDATOR_DIR, CAPS_BASENAME)

// In-container mount points (see ModuleService buildAndUp). The DIRECTORY is
// what gets mounted; the file path the hub reads is unchanged from when the
// file itself was mounted, so no hub-side change is needed.
const CAPS_CONTAINER_DIR  = '/validator'
const CAPS_CONTAINER_PATH = CAPS_CONTAINER_DIR + '/' + CAPS_BASENAME

// The two coin wallets and the DOGE signer module. The signer directory is
// what the hub container mounts (read-only, at SIGNER_CONTAINER_DIR), so the
// stake WIF deliberately lives OUTSIDE it in wallets.env: the hub never needs
// the stake key, so the hub never sees it.
const WALLETS_FILE         = path.join(VALIDATOR_DIR, 'wallets.env')
const SIGNER_DIR           = path.join(VALIDATOR_DIR, 'signer')
const SIGNER_FILE          = path.join(SIGNER_DIR, 'signer.js')
const SIGNER_ENV_FILE      = path.join(SIGNER_DIR, '.env')

// The mountpoint the SDK is mounted onto, INSIDE the read-only signer mount.
// It must exist on the host before the container starts: docker mounts the
// parent first, and creating a missing mountpoint under a read-only bind mount
// fails with "make mountpoint: read-only file system", which does not degrade
// to a hub without a signer, it aborts container creation outright. Measured
// against the real hub image.
const SIGNER_MODULES_DIR   = path.join(SIGNER_DIR, 'node_modules')
const SIGNER_CONTAINER_DIR = '/XChainHub/operator-signer'
const SIGNER_CONTAINER_PATH = SIGNER_CONTAINER_DIR + '/signer.js'

// The P2P port names the federation: one host can serve both networks later,
// so the port is the declared split rather than anything the protocol enforces.
const NETWORK_BY_P2P_PORT = { 10001: 'mainnet', 10002: 'testnet' }
const P2P_PORT_BY_NETWORK = { mainnet: 10001, testnet: 10002 }

// Oracle round-numbering anchor per federation. A hub with a different value
// computes different round numbers and its submissions never line up, so the
// known federations' values are defaults here; --oracle-epoch-start overrides.
// testnet: read from the live validator01-05 containers on 2026-08-29.
const ORACLE_EPOCH_START_BY_NETWORK = { testnet: 1787875200000 }

// SDK network names and public encoder coin prefixes per hub network.
const COIN_NETWORKS = {
    mainnet: { stake: 'bitcoin-mainnet', doge: 'dogecoin-mainnet', stakeCoin: 'BTC',  dogeCoin: 'DOGE'  },
    testnet: { stake: 'bitcoin-testnet', doge: 'dogecoin-testnet', stakeCoin: 'TBTC', dogeCoin: 'TDOGE' },
    regtest: { stake: 'bitcoin-regtest', doge: 'dogecoin-regtest', stakeCoin: 'BTC',  dogeCoin: 'DOGE'  }
}
const PUBLIC_ENCODER_BASE = 'https://encoder.xchain.io/'

// ROLLCALL: every epoch (1008 BTC blocks, 30 on regtest) each validator signs
// a message over that epoch's ledger_hash; the elected leader publishes the
// collected signatures on DOGE, and the BTC indexer closes the epoch and
// evicts a staking source absent for K=2 consecutive rolled epochs. Every
// ROLLCALL payload exceeds the 76-byte OP_RETURN cap, so it always rides the
// chunked two-phase P2SH lane - two transactions, ~0.003 DOGE each - which is
// where the per-call DOGE cost below comes from. It spends from the same
// publisher wallet anchors already use; no separate wallet or key.
const ROLLCALL_DOGE_COST_PER_CALL = 0.006
// BTC blocks per ROLLCALL epoch, network-keyed. An absence read only ever
// returns absent epochs, so two rows are a true back-to-back streak only when
// their epoch_height values are exactly one epoch apart; any other gap means
// a rolled (present) epoch fell between them, however close the rows sit in
// the array.
const ROLLCALL_EPOCH_BLOCKS = { regtest: 30, testnet: 1008, mainnet: 1008 }
const ROLLCALL_EPOCH_BLOCKS_DEFAULT = 1008

// Lazy: the SDK pulls in the whole bitcoinjs stack, and every validator
// subcommand that does not touch a wallet (status) should not pay for it.
function loadSdk() {
    return require('@dankest-llc/xchain-sdk')
}

// Generate a fresh single-key wallet on the named SDK network, or import one
// from a WIF. Returns address + public key + WIF; the caller decides where the
// WIF is written and it is never printed.
function makeCoinWallet(sdkNetwork, wif) {
    const { XChainSDK } = loadSdk()
    const sdk  = new XChainSDK({ network: sdkNetwork })
    const keys = wif ? sdk.wallet.importWIF(wif) : sdk.wallet.generateKeyPair()
    return {
        address:   sdk.wallet.deriveAddress(keys.publicKey),
        pubkeyHex: keys.publicKeyHex,
        wif:       keys.wif
    }
}

// Read a secret from the CONTROLLING TERMINAL with echo off. /dev/tty rather
// than stdin, so a pasted multi-line block cannot race the prompt. Returns
// null when there is no terminal, so a non-interactive caller gets a clear
// error naming the env var instead of a hang.
function promptSecret(promptText) {
    const { execFileSync } = require('child_process')
    let fd
    try { fd = fs.openSync('/dev/tty', 'rs') } catch { return null }
    let echoOff = false
    try { execFileSync('stty', ['-echo'], { stdio: [fd, 'ignore', 'ignore'] }); echoOff = true } catch { /* not a tty */ }
    process.stderr.write(promptText)
    const buf = Buffer.alloc(1)
    let out = ''
    try {
        for (;;) {
            let n = 0
            try { n = fs.readSync(fd, buf, 0, 1, null) }
            catch (e) { if (e.code === 'EAGAIN') continue; throw e }
            if (n === 0) break
            const ch = buf.toString('utf8')
            if (ch === '\n' || ch === '\r') break
            if (ch === '\u0003') { out = ''; break }
            if (ch === '\u007f') { out = out.slice(0, -1); continue }
            out += ch
        }
    } finally {
        if (echoOff) { try { execFileSync('stty', ['echo'], { stdio: [fd, 'ignore', 'ignore'] }) } catch { /* best effort */ } }
        process.stderr.write('\n')
        try { fs.closeSync(fd) } catch { /* closed */ }
    }
    return out.trim()
}

// Resolve an operator-supplied WIF for one wallet: the env var first (the
// non-interactive path), then a hidden prompt. Throws when asked to import and
// neither is available, because silently generating instead would strand the
// coin the operator already funded at their own address.
function resolveImportedWif(label, envName, wantImport) {
    const fromEnv = process.env[envName]
    if (fromEnv) return fromEnv
    if (!wantImport) return null
    const typed = promptSecret('WIF for the ' + label + ' wallet (input hidden): ')
    if (!typed) {
        throw new Error('no WIF supplied for the ' + label + ' wallet. Type it at the prompt on a terminal, ' +
            'or set ' + envName + ' in the environment (never on the command line).')
    }
    return typed
}

// Parse a KEY=VALUE sidecar into an object. Comments and blank lines skipped.
function parseEnvText(text) {
    const out = {}
    for (const line of String(text || '').split(/\r?\n/)) {
        if (!line || line.startsWith('#')) continue
        const eq = line.indexOf('=')
        if (eq <= 0) continue
        out[line.substring(0, eq).trim()] = line.substring(eq + 1).trim()
    }
    return out
}

// The wallets file, or null when this validator has none (a pre-wallets init,
// or an operator running their own signer via XCHAIN_NODE_HUB_SIGNER_DIR).
function readWallets() {
    if (!isRegularFile(WALLETS_FILE)) return null
    try { return parseEnvText(fs.readFileSync(WALLETS_FILE, 'utf8')) } catch { return null }
}

// Addresses and public keys only: what `status` prints and what the hub env
// carries. The WIFs never leave the file through this path.
function publicWalletInfo(wallets) {
    if (!wallets) return null
    return {
        network:         wallets.NETWORK || null,
        stakeAddress:    wallets.STAKE_ADDRESS || null,
        stakePubkeyHex:  wallets.STAKE_PUBKEY_HEX || null,
        dogeAddress:     wallets.DOGE_ADDRESS || null,
        dogePubkeyHex:   wallets.DOGE_PUBKEY_HEX || null
    }
}

function writeWalletsFile(network, stake, doge) {
    const body = [
        '# xchain-node validator wallets, written by `xchain-node validator init`.',
        '# Mode 0600. BACK THIS FILE UP OFFLINE: there is no recovery for a lost key.',
        '# STAKE_* is the BTC wallet that funds fees, mints XCHAIN and holds the STAKE.',
        '# DOGE_* is the wallet the hub spends from to publish price rounds and anchors.',
        'NETWORK=' + network,
        'STAKE_ADDRESS=' + stake.address,
        'STAKE_PUBKEY_HEX=' + stake.pubkeyHex,
        'STAKE_WIF_SECRET=' + stake.wif,
        'DOGE_ADDRESS=' + doge.address,
        'DOGE_PUBKEY_HEX=' + doge.pubkeyHex,
        'DOGE_WIF_SECRET=' + doge.wif,
        ''
    ].join('\n')
    fs.writeFileSync(WALLETS_FILE, body, { mode: 0o600 })
    fs.chmodSync(WALLETS_FILE, 0o600)
}

// The HUB_SIGNER_MODULE the hub loads. Same contract as xchain-hub's
// examples/doge-signer.example.js (walletSign + the two-phase broadcast); kept
// here as a template so init works offline and the operator has one file to
// read if they want to replace it with their own signer.
const SIGNER_TEMPLATE = `/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 **********************************************************************
 *
 * HUB_SIGNER_MODULE written by \`xchain-node validator init\`.
 *
 * The hub's on-chain publishers (PRICE rounds, ANCHOR checkpoints) hand this
 * module a raw wire payload. It funds and reveals the two-phase P2SH encoding
 * through the encoder named in .env, signing with the DOGE publisher key that
 * lives beside this file. The key never enters the hub container's
 * environment: this directory is mounted read-only and only this module
 * reads it.
 *
 * Replace this file with your own signer if you keep keys elsewhere (an HSM,
 * a hardware wallet, a remote signing service). The contract is:
 *   walletSign(psbtHex) -> Promise<txHex>   REQUIRED
 *   broadcast(payload)  -> Promise<{txid}>  optional, replaces the default pipeline
 *   getBalance()        -> Promise<number>  optional, low-balance warnings
 *
 ********************************************************************/

const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const { XChainSDK } = require('@dankest-llc/xchain-sdk');

const NETWORK    = process.env.DOGE_NETWORK || '';
const WIF        = process.env.DOGE_WIF || '';
const ADDRESS    = process.env.DOGE_ADDRESS || '';
const ENCODER    = process.env.DOGE_ENCODER_URL || '';
const FEE_PER_KB = process.env.DOGE_FEE_PER_KB ? Number(process.env.DOGE_FEE_PER_KB) : undefined;

// Fail at load time: the hub treats a configured-but-broken signer as fatal,
// and a signer that cannot sign must not boot quietly.
for (const [name, value] of [['DOGE_NETWORK', NETWORK], ['DOGE_WIF', WIF], ['DOGE_ADDRESS', ADDRESS], ['DOGE_ENCODER_URL', ENCODER]]) {
    if (!value) throw new Error('doge-signer: ' + name + ' is not set in ' + path.join(__dirname, '.env'));
}

const sdk = new XChainSDK({ network: NETWORK, encoderUrl: ENCODER });

module.exports = {
    // Full publish pipeline for a raw wire payload string -> { txid }. The
    // returned txid is the phase-2 (reveal) txid when two-phase encoding is
    // used; that is the transaction indexers decode.
    async broadcast(payload) {
        const encoder = sdk._requireEncoder();

        const txParams = { data: payload, pubkey: ADDRESS, change: ADDRESS, encoding: 'P2SH' };
        if (FEE_PER_KB !== undefined) txParams.feePerKb = FEE_PER_KB;

        const encoded = await encoder.createTx(txParams);
        const signed  = sdk.wallet.signPsbt(encoded.psbt, WIF);
        await encoder.broadcastTx(signed.txHex);
        if (encoded.encoding !== 'P2SH' && encoded.encoding !== 'P2WSH')
            return { txid: signed.txid };

        const spendParams = {
            pubkey:   ADDRESS,
            p2shHash: signed.txid,
            p2shHex:  signed.txHex,
            data:     payload,
            encoding: encoded.encoding,
            change:   ADDRESS
        };
        if (FEE_PER_KB !== undefined) spendParams.feePerKb = FEE_PER_KB;
        const spendResult = await encoder.spendP2sh(spendParams);
        const spendSigned = sdk.wallet.signRevealPsbt(spendResult.psbt, WIF);
        await encoder.broadcastTx(spendSigned.txHex);

        return { txid: spendSigned.txid, phase1_txid: signed.txid };
    },

    // Sign an encoder-built PSBT -> signed raw tx hex. The hub's built-in
    // phase-1 pipeline and balance plumbing use this; broadcast() above takes
    // precedence when both are exported.
    async walletSign(psbtHex) {
        return sdk.wallet.signPsbt(psbtHex, WIF).txHex;
    }
};
`

function writeSignerDir(network, doge) {
    if (!fs.existsSync(SIGNER_DIR)) fs.mkdirSync(SIGNER_DIR, { recursive: true })
    ensureSignerModulesMountpoint()
    const coins = COIN_NETWORKS[network]
    fs.writeFileSync(SIGNER_FILE, SIGNER_TEMPLATE, { mode: 0o644 })
    const env = [
        '# DOGE publisher signer config, written by `xchain-node validator init`. Mode 0600.',
        '# DOGE_ENCODER_URL: the encoder that builds and relays the DOGE transactions.',
        '# The public XChain encoder is the default; point it at your own if you run one.',
        'DOGE_NETWORK=' + coins.doge,
        'DOGE_ADDRESS=' + doge.address,
        'DOGE_ENCODER_URL=' + (process.env.DOGE_ENCODER_URL || (PUBLIC_ENCODER_BASE + coins.dogeCoin)),
        'DOGE_WIF=' + doge.wif,
        ''
    ].join('\n')
    fs.writeFileSync(SIGNER_ENV_FILE, env, { mode: 0o600 })
    fs.chmodSync(SIGNER_ENV_FILE, 0o600)
}

function signerDirExists() {
    return isRegularFile(SIGNER_FILE) && isRegularFile(SIGNER_ENV_FILE)
}

// Create the empty node_modules directory the SDK mount lands on (see
// SIGNER_MODULES_DIR). Idempotent, and re-checked at mount time rather than
// only at init, so a config directory written before this existed still starts.
// An empty node_modules on the host is harmless outside the container: node
// keeps walking up the tree when a package is not found in it.
function ensureSignerModulesMountpoint() {
    if (!fs.existsSync(SIGNER_MODULES_DIR)) fs.mkdirSync(SIGNER_MODULES_DIR, { recursive: true })
}

// Host directory to mount at SIGNER_CONTAINER_DIR, or null. An operator who
// set XCHAIN_NODE_HUB_SIGNER_DIR runs their own signer and wins; the generated
// one is the default for everyone else. The signer requires the SDK, which is
// resolved from a node_modules mounted BESIDE it (ModuleService mounts this
// package's own node_modules there), so init never has to run npm.
function getSignerMountDir() {
    if (process.env.XCHAIN_NODE_HUB_SIGNER_DIR) return null
    if (!signerDirExists()) return null
    ensureSignerModulesMountpoint()
    return SIGNER_DIR
}

// The signer.js file actually in force: an operator-supplied module wins
// (same precedence as getSignerMountDir), else the generated one once init has
// written it. Null when neither is configured. Used for the roll-call
// broadcast check below, which reads this path rather than the mount dir.
function getActiveSignerFile() {
    if (process.env.XCHAIN_NODE_HUB_SIGNER_DIR) return path.join(process.env.XCHAIN_NODE_HUB_SIGNER_DIR, 'signer.js')
    return signerDirExists() ? SIGNER_FILE : null
}

// Strip comments before scanning a signer module's source, so a doc comment
// that merely mentions `broadcast(...)` (the generated template's own
// contract comment does exactly that, right above its module.exports) cannot
// be mistaken for the export itself.
function stripJsComments(src) {
    return String(src || '').replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '')
}

// Whether a signer module's module.exports names a `broadcast` export. Static
// only: this CLI never requires an operator-supplied signer file just to ask
// it a question, because that module's top-level code is meant to run inside
// the hub container (with its own env, its own SDK session) - not at
// `validator status` time, under whatever privileges ran the CLI. Returns
// null when there is no file to check.
function signerModuleExportsBroadcast(signerFilePath) {
    if (!signerFilePath || !isRegularFile(signerFilePath)) return null
    let src
    try { src = fs.readFileSync(signerFilePath, 'utf8') } catch { return null }
    const stripped = stripJsComments(src)
    if (/\bexports\.broadcast\s*=/.test(stripped)) return true
    // Scope the object-literal form (`broadcast(payload) {...}` or
    // `broadcast: ...` inside `module.exports = { ... }`) to text from the
    // LAST module.exports onward, so a `broadcast` named only in prose or a
    // helper earlier in the file cannot false-positive.
    const idx = stripped.lastIndexOf('module.exports')
    const tail = idx >= 0 ? stripped.slice(idx) : ''
    return /\bbroadcast\s*(?:\(|:)/.test(tail)
}

// The network this validator was initialized for: recorded on init, derived
// from the P2P port for installs that predate the field.
function resolveNetwork(opts, p2pPort) {
    const explicit = opts.network ? String(opts.network).toLowerCase() : null
    if (explicit && !COIN_NETWORKS[explicit]) {
        throw new Error('--network must be one of mainnet, testnet, regtest (got ' + opts.network + ')')
    }
    if (explicit) return explicit
    return NETWORK_BY_P2P_PORT[p2pPort] || null
}

// ASN.1 DER prefixes for Ed25519 (same as xchain-hub/src/ValidatorIdentity.js),
// so the pubkey we print matches what the hub derives from the same seed.
const PKCS8_ED25519_PREFIX = Buffer.from('302e020100300506032b657004220420', 'hex')
const SPKI_ED25519_PREFIX  = Buffer.from('302a300506032b6570032100', 'hex')

// Derive the 64-hex public key from a 64-hex Ed25519 seed.
function pubkeyFromSeedHex(seedHex) {
    const pkcs8 = Buffer.concat([PKCS8_ED25519_PREFIX, Buffer.from(seedHex, 'hex')])
    const priv  = crypto.createPrivateKey({ key: pkcs8, format: 'der', type: 'pkcs8' })
    const spki  = crypto.createPublicKey(priv).export({ format: 'der', type: 'spki' })
    return spki.subarray(SPKI_ED25519_PREFIX.length).toString('hex')
}

// Default capability config. MIN_STAKE thresholds mirror the indexer's
// authoritative governance config; the per-capability blocks satisfy the hub's
// self-tests. Operators tune capabilities.json after init (e.g. real RPC URLs).
function defaultCapabilityConfig(capabilities, wallets) {
    const enabled = new Set(capabilities)
    // The publisher block is filled from the DOGE wallet when init made one;
    // otherwise the placeholders stay and the operator edits them by hand.
    const dogeAddress = (wallets && wallets.dogeAddress) || 'REPLACE_WITH_DOGE_ADDRESS'
    const dogeWallet  = (wallets && wallets.dogeAddress) ? (SIGNER_CONTAINER_DIR + '/.env') : 'REPLACE_WITH_DOGE_WALLET_PATH'
    const allCaps = ['price', 'cross_chain', 'oracle_publish', 'attestation']
    return {
        // These MUST equal src/coins/BTC.js STAKING.CAPABILITIES MIN_STAKE
        // (the federation-uniform floors every hub sends the indexer as the
        // qualifying threshold). The hub asserts this at startup and refuses to
        // boot on mainnet/testnet if they diverge; cross_chain was 1000 here vs
        // the canonical 5000 for a while, which is the footgun that assert closes.
        CAPABILITIES: {
            price:          { MIN_STAKE: '1000.00000000' },
            cross_chain:    { MIN_STAKE: '5000.00000000' },
            oracle_publish: { MIN_STAKE: '500.00000000'  },
            attestation:    { MIN_STAKE: '1000.00000000' },
            // full_node is absent from allCaps below (a NODEPROOF tier, not an
            // opt-in capability) but its threshold still belongs here: omitting
            // one threshold makes the hub refuse to build ANY capability
            // snapshot, so every capability reads N=0 and the transport signer
            // set stays empty. Fail-closed, because a locally-chosen threshold
            // could qualify different validator sets for one round and fork.
            full_node:      { MIN_STAKE: '2000.00000000' }
        },
        // Capabilities the operator opted OUT of (qualified but won't serve).
        DISABLED_CAPABILITIES: allCaps.filter(c => !enabled.has(c)),
        // Self-test config blocks (presence-checked by the hub; live probing
        // happens during normal operation).
        price:          { sources: ['coingecko'], fiats: ['USD'] },
        cross_chain:    { chains: { BTC: { rpc: 'http://node:8332' } } },
        oracle_publish: { doge_address: dogeAddress, doge_wallet: dogeWallet },
        attestation:    { providers: {} }
    }
}

function isInitialized() {
    return fs.existsSync(SETTINGS_FILE) && fs.existsSync(KEY_FILE)
}

// True only for a real regular file (a directory at the same path is not one).
// Docker AUTO-CREATES a missing bind-mount source as a directory, so the legacy
// single-file mount leaves exactly that carcass behind on any host where the
// file was removed: existsSync() alone would call it a config file and migrate
// a directory over the live one.
function isRegularFile(p) {
    try { return fs.lstatSync(p).isFile() } catch { return false }
}

/**
 * Move a pre-hub-caps capabilities.json into its own directory.
 *
 * MIGRATE rather than copy: two files would drift, and the drift is silent
 * (the operator edits the path they know, the container reads the other one),
 * which is the failure class this row exists to remove. After this runs there
 * is exactly ONE capability config on disk.
 *
 * Idempotent, and safe to call on a non-validator node (does nothing).
 */
function ensureCapabilityConfigLayout() {
    const legacyIsFile = isRegularFile(LEGACY_CAPS_FILE)

    if (isRegularFile(CAPS_FILE)) {
        // Already migrated. A legacy file that reappeared (an old install run
        // against the same config dir) is NOT read by anything: say so rather
        // than let an operator tune a file the hub will never see.
        if (legacyIsFile) {
            console.log('WARNING: ignoring stale ' + LEGACY_CAPS_FILE
                + '; the live capability config is ' + CAPS_FILE + ' (delete the stale one)')
        }
        return false
    }

    if (!legacyIsFile) return false

    if (!fs.existsSync(CAPS_DIR)) fs.mkdirSync(CAPS_DIR, { recursive: true })
    fs.renameSync(LEGACY_CAPS_FILE, CAPS_FILE)
    console.log('Moved validator capability config to ' + CAPS_FILE
        + ' (its own directory, so the hub mount cannot break `docker cp`).')
    return true
}

/**
 * Refuse to mount CAPS_DIR if it holds anything but the capability config.
 *
 * The whole directory goes into the hub container, so an extra file here is an
 * unreviewed hand-off to the hub; signing.key landing here would put the
 * validator's PRIVATE KEY in the container. Throwing fails the install loudly:
 * a silent skip would boot a hub with no capability config at all.
 */
function assertCapsDirIsolated() {
    const extra = fs.readdirSync(CAPS_DIR).filter(name => name !== CAPS_BASENAME)
    if (extra.length > 0) {
        throw new Error('refusing to mount ' + CAPS_DIR + ' into the hub container: it must contain only '
            + CAPS_BASENAME + ', found ' + extra.join(', ')
            + '. Move those files back under ' + VALIDATOR_DIR + ' (the signing key MUST NOT be in this directory).')
    }
}

// One line of operator-facing output naming WHERE the hub credential lives. The value
// is never printed: an API key in a terminal is an API key in a scrollback buffer.
function reportHubApiKey(hubApiKey) {
    console.log('  hub API key : ' + hubApiKey.path
        + ' (mode 0600, key HUB_API_KEY, ' + (hubApiKey.generated ? 'generated now' : 'already present, reused') + ')')
}

/**
 * Set up the two coin wallets and the DOGE signer, or report why not.
 *
 * Shared by a fresh init and by a re-run over an already-initialized
 * validator, for the same reason ensureHubApiKey runs before the
 * already-initialized early return: a node initialized BEFORE wallets existed
 * is exactly the node that needs them, and making it rotate its signing key
 * (and therefore re-stake, and wait out the activation delay again) to get
 * them would be a punishing upgrade path for a working validator.
 *
 * An existing wallets.env is KEPT unless --force-wallets: the signing key is
 * cheap to replace, but a funded stake or publisher address is not, and
 * regenerating it strands the coin.
 */
function setupWallets(network, opts) {
    const out = { wallets: readWallets(), generated: false, imported: [], skippedNoNetwork: false }
    if (opts.wallets === false) return out
    if (!network) {
        // A non-standard port is a custom federation, and a wallet is only
        // meaningful on a known coin network. Importing a key is an explicit
        // ask, so that case fails loud; plain init just says what it skipped.
        if (opts.importStakeKey || opts.importDogeKey || opts.forceWallets) {
            throw new Error('cannot set up wallets without knowing the network: pass --network testnet|mainnet, ' +
                'or --p2p-port 10002 (testnet) / 10001 (mainnet).')
        }
        out.skippedNoNetwork = true
        return out
    }
    if (out.wallets && !opts.forceWallets) return out

    const coins = COIN_NETWORKS[network]
    const stakeWif = resolveImportedWif('stake (BTC)', 'XCHAIN_NODE_STAKE_WIF', !!opts.importStakeKey)
    const dogeWif  = resolveImportedWif('DOGE publisher', 'XCHAIN_NODE_DOGE_WIF', !!opts.importDogeKey)
    const stake = makeCoinWallet(coins.stake, stakeWif)
    const doge  = makeCoinWallet(coins.doge, dogeWif)
    if (stakeWif) out.imported.push('stake')
    if (dogeWif)  out.imported.push('DOGE')
    writeWalletsFile(network, stake, doge)
    writeSignerDir(network, doge)
    out.wallets = readWallets() || {
        NETWORK: network, STAKE_ADDRESS: stake.address, STAKE_PUBKEY_HEX: stake.pubkeyHex,
        DOGE_ADDRESS: doge.address, DOGE_PUBKEY_HEX: doge.pubkeyHex
    }
    out.generated = true
    return out
}

// Print the two funding addresses. Addresses only: the keys stay in the file.
function reportWallets(walletInfo, network, verb) {
    const coins = COIN_NETWORKS[(walletInfo && walletInfo.network) || network] || COIN_NETWORKS.mainnet
    console.log('  Wallets ' + verb + '. Fund these two addresses:')
    console.log('    stake / fees   (' + coins.stakeCoin + ') : ' + walletInfo.stakeAddress)
    console.log('    price + anchor (' + coins.dogeCoin  + ') : ' + walletInfo.dogeAddress)
}

// Generate a key + write all validator files. Idempotent guard via `force`.
async function initValidator(opts = {}) {
    // A validator-mode hub REFUSES TO BOOT with no HUB_API_KEY, so init has to leave one
    // behind or this whole ceremony ends in a node that cannot start. Done BEFORE the
    // already-initialized early return, because a node initialized before this existed is
    // exactly the node sitting in that refused-boot state; re-running init repairs it.
    const hubApiKey = await ensureHubApiKey()

    if (isInitialized() && !opts.force) {
        const existing = JSON.parse(fs.readFileSync(SETTINGS_FILE, 'utf8'))
        console.log('Validator already initialized. Pubkey: ' + existing.pubkey)
        reportHubApiKey(hubApiKey)

        // REPAIR, never rotate. Everything below is additive: it fills in what
        // a validator from an older version is missing and leaves the signing
        // key, and therefore the stake, alone.
        const network = resolveNetwork(opts, parseInt(opts.p2pPort) || existing.P2P_PORT || 0)
            || existing.network || NETWORK_BY_P2P_PORT[existing.P2P_PORT] || null

        // The hub refuses to boot in validator mode without HUB_NETWORK, and
        // getValidatorEnv can only supply it from a recorded network.
        if (!existing.network && network) {
            existing.network = network
            fs.writeFileSync(SETTINGS_FILE, JSON.stringify(existing, null, 2))
            console.log('  network     : recorded as ' + network + ' (derived from P2P port ' + existing.P2P_PORT + ')')
        }

        const w = setupWallets(network, opts)
        const walletInfo = publicWalletInfo(w.wallets)
        if (w.generated) {
            ensureCapabilityConfigLayout()
            fillPublisherConfig(walletInfo)
        }
        console.log('')
        if (walletInfo) {
            reportWallets(walletInfo, network, w.generated
                ? (w.imported.length ? 'imported (' + w.imported.join(', ') + ')' : 'generated now')
                : 'already present')
            if (w.generated) {
                console.log('')
                console.log('  Next: xchain-node validator stake      (dry run shows balances and the plan)')
            }
        } else if (w.skippedNoNetwork) {
            console.log('  No wallets, and the network is unknown for port ' + existing.P2P_PORT + '.')
            console.log('  Re-run with --network testnet|mainnet to generate them.')
        }
        console.log('')
        console.log('Re-run with --force to regenerate the SIGNING KEY (that creates a NEW key; you would need to re-stake).')
        console.log('Wallets are never replaced by --force; --force-wallets does that, abandoning the old addresses.')
        return existing
    }

    if (!fs.existsSync(VALIDATOR_DIR)) fs.mkdirSync(VALIDATOR_DIR, { recursive: true })
    if (!fs.existsSync(CAPS_DIR)) fs.mkdirSync(CAPS_DIR, { recursive: true })
    // An init over a pre-hub-caps install must adopt that install's tuned
    // config, not silently start beside it.
    ensureCapabilityConfigLayout()

    const seedHex = crypto.randomBytes(32).toString('hex')
    const pubkey  = pubkeyFromSeedHex(seedHex)

    const capabilities = String(opts.capabilities || 'price,cross_chain,oracle_publish,attestation')
        .split(',').map(s => s.trim()).filter(Boolean)
    let seedNodes = String(opts.seedNodes || '')
        .split(',').map(s => s.trim()).filter(Boolean)

    // --network names the federation; the P2P port follows it (or names it, for
    // callers who only passed a port). Neither given keeps the historical
    // mainnet default of 10001.
    const explicitNetwork = resolveNetwork(opts, parseInt(opts.p2pPort) || 0)
    const p2pPort = parseInt(opts.p2pPort)
        || (explicitNetwork && P2P_PORT_BY_NETWORK[explicitNetwork])
        || 10001
    const network = explicitNetwork || NETWORK_BY_P2P_PORT[p2pPort] || null

    // A validator with no seeds dials nobody and joins no gossip mesh, while
    // looking healthy. Default to the bootstrap set; --seed-nodes overrides.
    // The PORT selects the network, so a wrong port reaches the wrong federation.
    let seedNodesDefaulted = false
    if (seedNodes.length === 0 && (p2pPort === 10001 || p2pPort === 10002)) {
        seedNodes = ['01','02','03','04','05'].map(n => 'ws://validator' + n + '.xchain.io:' + p2pPort)
        seedNodesDefaulted = true
    }

    // Oracle round numbering anchor. MUST match across the federation, so a
    // known federation's value is the default and --oracle-epoch-start overrides.
    let oracleEpochStart = opts.oracleEpochStart ? parseInt(opts.oracleEpochStart) : null
    let oracleEpochDefaulted = false
    if (!oracleEpochStart && network && ORACLE_EPOCH_START_BY_NETWORK[network]) {
        oracleEpochStart = ORACLE_EPOCH_START_BY_NETWORK[network]
        oracleEpochDefaulted = true
    }

    const settings = {
        enabled:            true,
        pubkey:             pubkey,
        network:            network,
        P2P_VALIDATOR_ADDR: opts.p2pAddr || ('0.0.0.0:' + p2pPort),
        P2P_PORT:           p2pPort,
        SEED_NODES:         seedNodes,
        ORACLE_EPOCH_START: oracleEpochStart,
        capabilities:       capabilities
    }

    // The two coin wallets and the DOGE signer (see setupWallets).
    const walletSetup = setupWallets(network, opts)
    const walletsGenerated = walletSetup.generated
    const walletsImported  = walletSetup.imported
    const walletsSkippedNoNetwork = walletSetup.skippedNoNetwork
    const walletInfo = publicWalletInfo(walletSetup.wallets)

    // Write the secret key first, locked down, and never echo it.
    fs.writeFileSync(KEY_FILE, seedHex, { mode: 0o600 })
    fs.chmodSync(KEY_FILE, 0o600)
    fs.writeFileSync(SETTINGS_FILE, JSON.stringify(settings, null, 2))
    if (!fs.existsSync(CAPS_FILE) || opts.force) {
        fs.writeFileSync(CAPS_FILE, JSON.stringify(defaultCapabilityConfig(capabilities, walletInfo), null, 2))
    } else if (walletsGenerated) {
        fillPublisherConfig(walletInfo)
    }

    console.log('')
    console.log('Validator initialized' + (network ? ' for ' + network : '') + '.')
    console.log('  signing key : ' + KEY_FILE + ' (mode 0600, keep this secret and back it up)')
    console.log('  settings    : ' + SETTINGS_FILE)
    console.log('  capabilities: ' + CAPS_FILE)
    reportHubApiKey(hubApiKey)
    if (walletInfo) {
        console.log('  wallets     : ' + WALLETS_FILE + ' (mode 0600, holds both private keys: BACK IT UP)')
        console.log('  DOGE signer : ' + SIGNER_DIR + ' (mounted read-only into the hub)')
    }
    console.log('')
    console.log('  PUBKEY (stake XCHAIN to this to qualify capabilities):')
    console.log('    ' + pubkey)
    console.log('')
    if (walletInfo) {
        reportWallets(walletInfo, network, walletsGenerated
            ? (walletsImported.length ? 'imported (' + walletsImported.join(', ') + ')' : 'generated')
            : 'already present, kept')
        console.log('')
        console.log('  Then: xchain-node validator stake            (mints XCHAIN on testnet, then stakes)')
        console.log('        xchain-node install ' + RELEASE_REF + ' xchain-hub  (starts the validator)')
    } else if (walletsSkippedNoNetwork) {
        console.log('  Wallets skipped: the network is unknown for port ' + p2pPort + '. Re-run with --network testnet|mainnet')
        console.log('  to generate them, or run your own signer via XCHAIN_NODE_HUB_SIGNER_DIR.')
    } else {
        console.log('  Wallets skipped (--no-wallets). Run your own signer via XCHAIN_NODE_HUB_SIGNER_DIR')
        console.log('  and set oracle_publish.doge_address in ' + CAPS_FILE + ' by hand.')
        console.log('  Then: xchain-node install ' + RELEASE_REF + ' xchain-hub')
    }
    console.log('')
    if (!settings.ORACLE_EPOCH_START)
        console.log('  NOTE: set ORACLE_EPOCH_START (--oracle-epoch-start <unix-ms>) to the value shared by your federation before running the oracle.')
    else if (oracleEpochDefaulted)
        console.log('  ORACLE_EPOCH_START: defaulted to the ' + network + ' federation value ' + oracleEpochStart + '.')
    if (seedNodes.length === 0)
        console.log('  NOTE: no SEED_NODES set. Add peer addresses (--seed-nodes host:port,...) to join the gossip mesh.')
    else if (seedNodesDefaulted)
        console.log('  SEED_NODES: defaulted to the five validator01-05.xchain.io bootstrap peers on port ' +
                    p2pPort + '. Override with --seed-nodes host:port,... if you peer elsewhere.')
    if (!network)
        console.log('  NOTE: network unknown (non-standard port). The hub needs HUB_NETWORK in the host .env.')
    console.log('  cross_chain needs a BTC RPC endpoint in ' + CAPS_FILE + ' or must be listed under DISABLED_CAPABILITIES.')
    console.log('')

    return settings
}

// Point an existing capabilities.json at the DOGE wallet init just made,
// leaving every other operator edit alone. Only the two placeholder values
// are touched: a hand-set address is the operator's and stays.
function fillPublisherConfig(walletInfo) {
    if (!walletInfo || !walletInfo.dogeAddress || !isRegularFile(CAPS_FILE)) return false
    let caps
    try { caps = JSON.parse(fs.readFileSync(CAPS_FILE, 'utf8')) } catch { return false }
    const entry = caps.oracle_publish || (caps.oracle_publish = {})
    let changed = false
    if (!entry.doge_address || entry.doge_address === 'REPLACE_WITH_DOGE_ADDRESS') {
        entry.doge_address = walletInfo.dogeAddress; changed = true
    }
    if (!entry.doge_wallet || entry.doge_wallet === 'REPLACE_WITH_DOGE_WALLET_PATH') {
        entry.doge_wallet = SIGNER_CONTAINER_DIR + '/.env'; changed = true
    }
    if (changed) fs.writeFileSync(CAPS_FILE, JSON.stringify(caps, null, 2))
    return changed
}

// Read persisted validator settings (or null if not initialized / disabled).
function getValidatorSettings() {
    if (!isInitialized()) return null
    try {
        const s = JSON.parse(fs.readFileSync(SETTINGS_FILE, 'utf8'))
        return s && s.enabled ? s : null
    } catch { return null }
}

// Build the env-var fragment injected into the hub container when validator
// mode is enabled. Returns {} for standalone (no validator configured), so the
// standalone install is byte-for-byte unchanged.
function getValidatorEnv() {
    const s = getValidatorSettings()
    if (!s) return {}
    const env = {
        P2P_VALIDATOR_ADDR: s.P2P_VALIDATOR_ADDR,
        P2P_PORT:           s.P2P_PORT,
        SEED_NODES:         (s.SEED_NODES || []).join(','),
        SIGNING_PRIVKEY_HEX: fs.readFileSync(KEY_FILE, 'utf8').trim(),
        HUB_CAPABILITY_CONFIG: CAPS_CONTAINER_PATH
    }
    if (s.ORACLE_EPOCH_START) env.ORACLE_EPOCH_START = s.ORACLE_EPOCH_START

    // The hub refuses to boot in validator mode without HUB_NETWORK. Host env
    // wins (the passthrough list already copied it); the recorded network
    // fills the gap so a fresh install needs no .env edit for it.
    if (!process.env.HUB_NETWORK && s.network) env.HUB_NETWORK = s.network

    // DOGE publisher wiring, from the wallet init made. Every value here is
    // public (address, pubkey, encoder URL); the WIF stays in the mounted
    // signer directory. Host env wins on each, so an operator running their
    // own publisher is not overridden.
    const w = publicWalletInfo(readWallets())
    if (w && w.dogeAddress) {
        const coins = COIN_NETWORKS[w.network || s.network] || null
        env.DOGE_ADDRESS    = process.env.DOGE_ADDRESS    || w.dogeAddress
        env.DOGE_PUBKEY_HEX = process.env.DOGE_PUBKEY_HEX || w.dogePubkeyHex
        env.DOGE_ENCODER_URL = process.env.DOGE_ENCODER_URL
            || (coins ? PUBLIC_ENCODER_BASE + coins.dogeCoin : '')
        if (!env.DOGE_ENCODER_URL) delete env.DOGE_ENCODER_URL
    }
    if (getSignerMountDir()) env.HUB_SIGNER_MODULE = SIGNER_CONTAINER_PATH
    return env
}

// Host path of capabilities.json (the file the operator edits), or null.
// Migrates a legacy layout first, so this always names the file the hub reads.
function getCapabilityConfigHostPath() {
    if (!getValidatorSettings()) return null
    ensureCapabilityConfigLayout()
    return isRegularFile(CAPS_FILE) ? CAPS_FILE : null
}

// Host DIRECTORY to bind-mount into the hub container (or null when this node
// is not a validator / has no capability config yet). A directory, not the
// file: a single-file bind mount breaks `docker cp` against the container for
// every path, forever. Verified isolated before it is handed over.
function getCapabilityConfigMountDir() {
    if (!getCapabilityConfigHostPath()) return null
    assertCapsDirIsolated()
    return CAPS_DIR
}

function rollcallEpochBlocks(network) {
    return ROLLCALL_EPOCH_BLOCKS[network] || ROLLCALL_EPOCH_BLOCKS_DEFAULT
}

// Count the consecutive absences from the HEAD of an epoch_height-DESC
// absence list (the read is ordered that way; see getRollcallStatus). The
// read only ever returns absent epochs, so two rows are truly back-to-back
// in time only when they are exactly one epoch's worth of blocks apart;
// anything else means a rolled (present) epoch fell between them and the
// streak broke there, no matter how close together the two rows sit in the
// array. Only the run starting at index 0 counts - an old streak buried
// deeper in the history is not this key's CURRENT exposure.
function rollcallAbsenceStreak(absences, epochBlocks) {
    const rows = Array.isArray(absences) ? absences : []
    if (!rows.length) return 0
    let streak = 1
    for (let i = 1; i < rows.length; i++) {
        const gap = Number(rows[i - 1].epoch_height) - Number(rows[i].epoch_height)
        if (gap !== epochBlocks) break
        streak++
    }
    return streak
}

/**
 * Everything `validator status` needs to report ROLLCALL health, gathered in
 * one pass:
 *   - the DOGE publisher's roll-call runway, from the SAME balance read
 *     anchors already report (never a second fetch);
 *   - whether the configured signer can PUBLISH a roll call rather than only
 *     sign one (the trap: every ROLLCALL payload exceeds the 76-byte
 *     OP_RETURN cap, so it always needs the chunked two-phase P2SH lane, and
 *     the hub's built-in broadcast pipeline only finishes phase 1 there);
 *   - this key's BTC-side absence streak, read from the indexer's public
 *     getrollcallabsences({source, limit}) -> {absences: [...]}.
 *
 * Each of the three degrades independently to an "unavailable" shape rather
 * than throwing: one read failing (an unreachable indexer, an older indexer
 * without this read yet) must not hide the other two, and must never read as
 * a reassuring zero.
 *
 * `deps.makeSdk(sdkNetwork)` lets tests inject a fake SDK without touching the
 * network, the same shape ValidatorStakeService's tests already use.
 */
async function getRollcallStatus(walletInfo, network, deps = {}) {
    const coins = COIN_NETWORKS[network] || null
    const out = { doge: null, broadcast: null, absences: null }

    const signerFile = deps.getActiveSignerFile ? deps.getActiveSignerFile() : getActiveSignerFile()
    if (signerFile) out.broadcast = { file: signerFile, exportsBroadcast: signerModuleExportsBroadcast(signerFile) }

    if (!walletInfo || !coins) return out

    const { XChainSDK } = deps.sdk || loadSdk()
    const makeSdk = deps.makeSdk || (sdkNetwork => new XChainSDK({ network: sdkNetwork }))

    if (walletInfo.dogeAddress) {
        try {
            const dogeSdk = makeSdk(coins.doge)
            const addr = await dogeSdk.explorer.getAddress(walletInfo.dogeAddress)
            const balance = Number(addr && addr.balances && addr.balances.confirmed)
            const safeBalance = Number.isFinite(balance) ? balance : 0
            out.doge = {
                unavailable: false,
                balance: safeBalance,
                rollcalls: Math.floor(safeBalance / ROLLCALL_DOGE_COST_PER_CALL)
            }
        } catch (e) {
            out.doge = { unavailable: true, error: e.message }
        }
    }

    if (walletInfo.stakeAddress) {
        try {
            const btcSdk = makeSdk(coins.stake)
            if (typeof btcSdk.explorer.getRollcallAbsences !== 'function') {
                // Older indexer: the read is not there yet, not "no absences".
                out.absences = { unavailable: true, reason: 'this indexer does not expose roll-call absence reads yet' }
            } else {
                const r = await btcSdk.explorer.getRollcallAbsences({ source: walletInfo.stakeAddress, limit: 20 })
                const rows = (r && Array.isArray(r.absences)) ? r.absences : []
                out.absences = {
                    unavailable: false,
                    streak: rollcallAbsenceStreak(rows, rollcallEpochBlocks(network)),
                    // The chain's own flag on the most recent absence, read directly
                    // rather than re-derived from the streak count, since it is the
                    // authoritative answer to "did THIS absence complete the K=2 run".
                    evictedNow: rows.length > 0 && Number(rows[0].evicted) === 1
                }
            }
        } catch (e) {
            out.absences = { unavailable: true, error: e.message }
        }
    }

    return out
}

module.exports = {
    initValidator,
    // Exported so a multi-validator deployment (the project's own colocated seed
    // validators) can generate the SAME capabilities.json a community operator
    // gets from `validator init`, instead of hand-rolling a second copy that
    // drifts. One hub per xchain-node install makes `init` itself unusable there,
    // but the CONFIG has no reason to differ, and a divergent MIN_STAKE here is a
    // consensus fork rather than a local misconfiguration.
    defaultCapabilityConfig,
    getValidatorSettings,
    getValidatorEnv,
    getCapabilityConfigHostPath,
    getCapabilityConfigMountDir,
    ensureCapabilityConfigLayout,
    isInitialized,
    pubkeyFromSeedHex,
    // Wallets: addresses out, WIFs only to the caller that must sign.
    readWallets,
    publicWalletInfo,
    getSignerMountDir,
    ensureSignerModulesMountpoint,
    fillPublisherConfig,
    promptSecret,
    loadSdk,
    COIN_NETWORKS,
    PUBLIC_ENCODER_BASE,
    CAPS_CONTAINER_PATH,
    CAPS_CONTAINER_DIR,
    CAPS_DIR,
    VALIDATOR_DIR,
    WALLETS_FILE,
    SIGNER_DIR,
    SIGNER_CONTAINER_DIR,
    // Roll-call status reporting (`validator status`).
    getRollcallStatus,
    getActiveSignerFile,
    signerModuleExportsBroadcast,
    rollcallAbsenceStreak,
    rollcallEpochBlocks,
    ROLLCALL_DOGE_COST_PER_CALL
}
