/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 * XChain Node - Validator Service
 *
 * Validator-mode onboarding for the xchain-hub. `validator init` generates
 * an Ed25519 signing key and writes the validator config that install/start
 * inject into the hub container so it runs as a full validator (P2P + PBFT +
 * capability staking) instead of a standalone config oracle.
 *
 * Files (under configDir/validator/):
 *   signing.key                 64-hex Ed25519 seed (mode 0600): SIGNING_PRIVKEY_HEX
 *   validator.json              P2P + oracle settings + enabled flag + pubkey
 *   hub-caps/capabilities.json  HUB_CAPABILITY_CONFIG: MIN_STAKE thresholds +
 *                               self-test blocks
 *   wallets.env                 the two coin wallets (mode 0600): the BTC stake
 *                               wallet (funds fees, mints and holds the STAKE)
 *                               and the DOGE publisher wallet (pays for price
 *                               rounds and anchors). Generated by init, or
 *                               imported from operator-supplied WIFs.
 *   signer/signer.js + .env     the HUB_SIGNER_MODULE the hub loads to sign
 *                               DOGE publishes. Mounted read-only into the
 *                               container; the WIF stays in this directory.
 *
 * Both wallets are ordinary single-key P2PKH wallets, so an operator who wants
 * a branded (vanity) address generates the key elsewhere and imports the WIF:
 * `--import-stake-key` / `--import-doge-key` prompt for it with echo off, and
 * XCHAIN_NODE_STAKE_WIF / XCHAIN_NODE_DOGE_WIF carry it non-interactively.
 * Never as an argv value: a WIF in argv is a WIF in every process listing.
 *
 * The hub's API key is deliberately NOT one of these. A hub refuses to boot
 * without HUB_API_KEY unless keyless operation is declared, so a FRESH init
 * mints one, but it belongs to the HOST rather than to this validator identity:
 * the local indexer and the shared services authenticate to the same hub with
 * the same value. It therefore lives in the shared 0600 sidecar config/hub.local
 * alongside HUB_DB_PASS (ConfigService.ensureHubApiKey). A RE-RUN over an
 * already-initialized node only READS it (ConfigService.readHubApiKey): see
 * initValidator for why minting there breaks a keyless deployment.
 *
 * Why capabilities.json sits in its own `hub-caps/` subdirectory rather than
 * beside the other two: the hub container mounts it, and a SINGLE-FILE bind
 * mount breaks `docker cp` against that container forever. Docker's copy path
 * recreates every mount destination as a directory, so it hits the existing
 * file and aborts the whole operation with
 * "mkdirat validator/capabilities.json: file exists" - for ANY path copied,
 * not just the mounted one. Mounting a DIRECTORY instead has no such problem.
 * The directory that gets mounted must therefore contain the capability config
 * and NOTHING else: mounting `validator/` itself would put signing.key, the
 * validator's private key, inside the hub container. ensureCapabilityConfigLayout()
 * migrates pre-hub-caps installs, and assertCapsDirIsolated() refuses to build
 * the mount if anything else ever lands in that directory.
 *
 * The private key is never logged. Only the PUBLIC key is printed (operators
 * stake to it).
 ********************************************************************/

const fs = require('fs')
const path = require('path')
const crypto = require('crypto')
const childProcess = require('child_process')
const { configDir } = require('../config')
const config = require('../config')
const { getLogger } = require('../observability/logger')
const logger = getLogger()
const { ensureHubApiKey, readHubApiKey } = require('./config_service')

const validatorPaths = require('./validator_service/validator_paths.js')
validatorPaths.configureDependencies({ fs, path, configDir })
const {
    VALIDATOR_DIR, RELEASE_REF, KEY_FILE, SETTINGS_FILE, CAPS_BASENAME, CAPS_DIR,
    CAPS_FILE, LEGACY_CAPS_FILE, CAPS_CONTAINER_DIR, CAPS_CONTAINER_PATH,
    WALLETS_FILE, SIGNER_DIR, SIGNER_FILE, SIGNER_ENV_FILE, SIGNER_MODULES_DIR,
    SIGNER_CONTAINER_DIR, SIGNER_CONTAINER_PATH, NETWORK_BY_P2P_PORT,
    P2P_PORT_BY_NETWORK, ORACLE_EPOCH_START_BY_NETWORK, COIN_NETWORKS,
    PUBLIC_ENCODER_BASE, isRegularFile
} = validatorPaths

const wallets = require('./validator_service/wallets.js')
wallets.configureDependencies({ fs, childProcess, config, WALLETS_FILE, isRegularFile })
const { loadSdk, makeCoinWallet, promptSecret, resolveImportedWif, readWallets, publicWalletInfo, writeWalletsFile } = wallets

const signer = require('./validator_service/signer.js')
signer.configureDependencies({ fs, path, config, SIGNER_DIR, SIGNER_FILE, SIGNER_ENV_FILE, COIN_NETWORKS, PUBLIC_ENCODER_BASE, isRegularFile, SIGNER_MODULES_DIR })
const { writeSignerDir, getSignerMountDir, getActiveSignerFile, signerModuleExportsBroadcast } = signer

const capabilityLayout = require('./validator_service/capability_layout.js')
capabilityLayout.configureDependencies({ fs, crypto, NETWORK_BY_P2P_PORT, COIN_NETWORKS, SIGNER_CONTAINER_DIR, KEY_FILE, SETTINGS_FILE, CAPS_DIR, CAPS_FILE, LEGACY_CAPS_FILE, isRegularFile, VALIDATOR_DIR, CAPS_BASENAME, getLogger, logger })
const { resolveNetwork, pubkeyFromSeedHex, defaultCapabilityConfig, isInitialized, ensureCapabilityConfigLayout, assertCapsDirIsolated, fillPublisherConfig } = capabilityLayout

const init = require('./validator_service/init_validator.js')
init.configureDependencies({ fs, crypto, ensureHubApiKey, readHubApiKey, COIN_NETWORKS, VALIDATOR_DIR, RELEASE_REF, KEY_FILE, SETTINGS_FILE, CAPS_DIR, CAPS_FILE, WALLETS_FILE, SIGNER_DIR, NETWORK_BY_P2P_PORT, P2P_PORT_BY_NETWORK, ORACLE_EPOCH_START_BY_NETWORK, makeCoinWallet, resolveImportedWif, readWallets, writeWalletsFile, publicWalletInfo, writeSignerDir, resolveNetwork, pubkeyFromSeedHex, defaultCapabilityConfig, isInitialized, ensureCapabilityConfigLayout, fillPublisherConfig, getLogger, logger })
const { initValidator } = init

const settings = require('./validator_service/validator_settings.js')
settings.configureDependencies({ fs, config, SETTINGS_FILE, KEY_FILE, CAPS_CONTAINER_PATH, SIGNER_CONTAINER_PATH, COIN_NETWORKS, PUBLIC_ENCODER_BASE, VALIDATOR_DIR, CAPS_FILE, isRegularFile, CAPS_DIR, isInitialized, ensureCapabilityConfigLayout, assertCapsDirIsolated, readWallets, publicWalletInfo, getSignerMountDir })
const { getValidatorSettings, getValidatorEnv, validatorModeReport, getCapabilityConfigHostPath, getCapabilityConfigMountDir } = settings

const drift = require('./validator_service/capability_drift.js')
drift.configureDependencies({ fs, config, SETTINGS_FILE, CAPS_FILE, COIN_NETWORKS, validatorModeReport, loadSdk })
const { capabilityDriftReport, capabilityDriftExitCode, formatCapabilityDrift, resolvedCapabilitySet, DRIFT_CAPABILITIES } = drift

const rollcall = require('./validator_service/rollcall.js')
rollcall.configureDependencies({ COIN_NETWORKS, loadSdk, getActiveSignerFile, signerModuleExportsBroadcast })
const { getRollcallStatus, rollcallAbsenceStreak, rollcallEpochBlocks } = rollcall

module.exports = {
    initValidator,
    // Exported so a multi-validator deployment (the project's own colocated seed
    // validators) can generate the SAME capabilities.json a community operator
    // gets from `validator init`, instead of hand-rolling a second copy that
    // drifts. One hub per xchain-node install makes `init` itself unusable there,
    // but the CONFIG has no reason to differ, and a divergent MIN_STAKE here is a
    // consensus fork rather than a local misconfiguration.
    defaultCapabilityConfig,
    getValidatorSettings,
    getValidatorEnv,
    validatorModeReport,
    // Capability-drift probe: resolved capability set vs the indexer's answer.
    capabilityDriftReport,
    capabilityDriftExitCode,
    formatCapabilityDrift,
    resolvedCapabilitySet,
    DRIFT_CAPABILITIES,
    getCapabilityConfigHostPath,
    getCapabilityConfigMountDir,
    ensureCapabilityConfigLayout,
    isInitialized,
    pubkeyFromSeedHex,
    // Wallets: addresses out, WIFs only to the caller that must sign.
    readWallets,
    publicWalletInfo,
    getSignerMountDir,
    promptSecret,
    loadSdk,
    COIN_NETWORKS,
    CAPS_CONTAINER_PATH,
    CAPS_CONTAINER_DIR,
    VALIDATOR_DIR,
    WALLETS_FILE,
    SIGNER_CONTAINER_DIR,
    // Roll-call status reporting (`validator status`).
    getRollcallStatus,
    getActiveSignerFile,
    signerModuleExportsBroadcast,
    rollcallAbsenceStreak,
    rollcallEpochBlocks
}

for (const part of ['validator_paths', 'wallets', 'signer', 'capability_layout', 'init_validator', 'validator_settings', 'capability_drift', 'rollcall']) {
    delete require.cache[require.resolve('./validator_service/' + part + '.js')]
}
