#Credentials
rpcuser=__XCHAIN_NODE_RPC_USER__
rpcpassword=__XCHAIN_NODE_RPC_PASSWORD__
#allow json-rpc requests
server=1
#index all transactions so users can retrieve them with the id
txindex=1
rpcport=8332
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0
rpctimeout=30
printtoconsole=1
listen=1
rpcworkqueue=128
rpcthreads=16