/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 * XChain Node - Validator Service
 *
 * Validator-mode onboarding for the xchain-hub. `validator init` generates
 * an Ed25519 signing key and writes the validator config that install/start
 * inject into the hub container so it runs as a full validator (P2P + PBFT +
 * capability staking) instead of a standalone config oracle.
 *
 * Files (under configDir/validator/):
 *   signing.key                 64-hex Ed25519 seed (mode 0600): SIGNING_PRIVKEY_HEX
 *   validator.json              P2P + oracle settings + enabled flag + pubkey
 *   hub-caps/capabilities.json  HUB_CAPABILITY_CONFIG: MIN_STAKE thresholds +
 *                               self-test blocks
 *   wallets.env                 the two coin wallets (mode 0600): the BTC stake
 *                               wallet (funds fees, mints and holds the STAKE)
 *                               and the DOGE publisher wallet (pays for price
 *                               rounds and anchors). Generated by init, or
 *                               imported from operator-supplied WIFs.
 *   signer/signer.js + .env     the HUB_SIGNER_MODULE the hub loads to sign
 *                               DOGE publishes. Mounted read-only into the
 *                               container; the WIF stays in this directory.
 *
 * Both wallets are ordinary single-key P2PKH wallets, so an operator who wants
 * a branded (vanity) address generates the key elsewhere and imports the WIF:
 * `--import-stake-key` / `--import-doge-key` prompt for it with echo off, and
 * XCHAIN_NODE_STAKE_WIF / XCHAIN_NODE_DOGE_WIF carry it non-interactively.
 * Never as an argv value: a WIF in argv is a WIF in every process listing.
 *
 * The hub's API key is deliberately NOT one of these. A hub refuses to boot
 * without HUB_API_KEY unless keyless operation is declared, so a FRESH init
 * mints one, but it belongs to the HOST rather than to this validator identity:
 * the local indexer and the shared services authenticate to the same hub with
 * the same value. It therefore lives in the shared 0600 sidecar config/hub.local
 * alongside HUB_DB_PASS (ConfigService.ensureHubApiKey). A RE-RUN over an
 * already-initialized node only READS it (ConfigService.readHubApiKey): see
 * initValidator for why minting there breaks a keyless deployment.
 *
 * Why capabilities.json sits in its own `hub-caps/` subdirectory rather than
 * beside the other two: the hub container mounts it, and a SINGLE-FILE bind
 * mount breaks `docker cp` against that container forever. Docker's copy path
 * recreates every mount destination as a directory, so it hits the existing
 * file and aborts the whole operation with
 * "mkdirat validator/capabilities.json: file exists" - for ANY path copied,
 * not just the mounted one. Mounting a DIRECTORY instead has no such problem.
 * The directory that gets mounted must therefore contain the capability config
 * and NOTHING else: mounting `validator/` itself would put signing.key, the
 * validator's private key, inside the hub container. ensureCapabilityConfigLayout()
 * migrates pre-hub-caps installs, and assertCapsDirIsolated() refuses to build
 * the mount if anything else ever lands in that directory.
 *
 * The private key is never logged. Only the PUBLIC key is printed (operators
 * stake to it).
 ********************************************************************/

let fs = require('fs')
let crypto = require('crypto')
let {
    NETWORK_BY_P2P_PORT, COIN_NETWORKS, SIGNER_CONTAINER_DIR, KEY_FILE,
    SETTINGS_FILE, CAPS_DIR, CAPS_FILE, LEGACY_CAPS_FILE, isRegularFile,
    VALIDATOR_DIR, CAPS_BASENAME
} = require('./validator_paths')
let { getLogger } = require('../../observability/logger')
let logger = getLogger()

// The network this validator was initialized for: recorded on init, derived
// from the P2P port for installs that predate the field.
function resolveNetwork(opts, p2pPort) {
    const explicit = opts.network ? String(opts.network).toLowerCase() : null
    if (explicit && !COIN_NETWORKS[explicit]) {
        throw new Error('--network must be one of mainnet, testnet, regtest (got ' + opts.network + ')')
    }
    if (explicit) return explicit
    return NETWORK_BY_P2P_PORT[p2pPort] || null
}

// ASN.1 DER prefixes for Ed25519 (same as xchain-hub/src/validators/identity.js),
// so the pubkey we print matches what the hub derives from the same seed.
const PKCS8_ED25519_PREFIX = Buffer.from('302e020100300506032b657004220420', 'hex')
const SPKI_ED25519_PREFIX  = Buffer.from('302a300506032b6570032100', 'hex')

// Derive the 64-hex public key from a 64-hex Ed25519 seed.
function pubkeyFromSeedHex(seedHex) {
    const pkcs8 = Buffer.concat([PKCS8_ED25519_PREFIX, Buffer.from(seedHex, 'hex')])
    const priv  = crypto.createPrivateKey({ key: pkcs8, format: 'der', type: 'pkcs8' })
    const spki  = crypto.createPublicKey(priv).export({ format: 'der', type: 'spki' })
    return spki.subarray(SPKI_ED25519_PREFIX.length).toString('hex')
}

// Default capability config. MIN_STAKE thresholds mirror the indexer's
// authoritative governance config; the per-capability blocks satisfy the hub's
// self-tests. Operators tune capabilities.json after init (e.g. real RPC URLs).
function defaultCapabilityConfig(capabilities, wallets) {
    const enabled = new Set(capabilities)
    // The publisher block is filled from the DOGE wallet when init made one;
    // otherwise the placeholders stay and the operator edits them by hand.
    const dogeAddress = (wallets && wallets.dogeAddress) || 'REPLACE_WITH_DOGE_ADDRESS'
    const dogeWallet  = (wallets && wallets.dogeAddress) ? (SIGNER_CONTAINER_DIR + '/.env') : 'REPLACE_WITH_DOGE_WALLET_PATH'
    const allCaps = ['price', 'cross_chain', 'oracle_publish', 'attestation']
    return {
        // These MUST equal src/coins/BTC.js STAKING.CAPABILITIES MIN_STAKE
        // (the federation-uniform floors every hub sends the indexer as the
        // qualifying threshold). The hub asserts this at startup and refuses to
        // boot on mainnet/testnet if they diverge; cross_chain was 1000 here vs
        // the canonical 5000 for a while, which is the footgun that assert closes.
        CAPABILITIES: {
            price:          { MIN_STAKE: '1000.00000000' },
            cross_chain:    { MIN_STAKE: '5000.00000000' },
            oracle_publish: { MIN_STAKE: '500.00000000'  },
            attestation:    { MIN_STAKE: '1000.00000000' },
            // full_node is absent from allCaps below (a NODEPROOF tier, not an
            // opt-in capability) but its threshold still belongs here: omitting
            // one threshold makes the hub refuse to build ANY capability
            // snapshot, so every capability reads N=0 and the transport signer
            // set stays empty. Fail-closed, because a locally-chosen threshold
            // could qualify different validator sets for one round and fork.
            full_node:      { MIN_STAKE: '2000.00000000' }
        },
        // Capabilities the operator opted OUT of (qualified but won't serve).
        DISABLED_CAPABILITIES: allCaps.filter(c => !enabled.has(c)),
        // Self-test config blocks (presence-checked by the hub; live probing
        // happens during normal operation).
        price:          { sources: ['coingecko'], fiats: ['USD'] },
        cross_chain:    { chains: { BTC: { rpc: 'http://node:8332' } } },
        oracle_publish: { doge_address: dogeAddress, doge_wallet: dogeWallet },
        attestation:    { providers: {} }
    }
}

function isInitialized() {
    return fs.existsSync(SETTINGS_FILE) && fs.existsSync(KEY_FILE)
}


/**
 * Move a pre-hub-caps capabilities.json into its own directory.
 *
 * MIGRATE rather than copy: two files would drift, and the drift is silent
 * (the operator edits the path they know, the container reads the other one),
 * which is the failure class this row exists to remove. After this runs there
 * is exactly ONE capability config on disk.
 *
 * Idempotent, and safe to call on a non-validator node (does nothing).
 */
function ensureCapabilityConfigLayout() {
    const legacyIsFile = isRegularFile(LEGACY_CAPS_FILE)

    if (isRegularFile(CAPS_FILE)) {
        // Already migrated. A legacy file that reappeared (an old install run
        // against the same config dir) is NOT read by anything: say so rather
        // than let an operator tune a file the hub will never see.
        if (legacyIsFile) {
            logger.info('WARNING: ignoring stale ' + LEGACY_CAPS_FILE
                + '; the live capability config is ' + CAPS_FILE + ' (delete the stale one)')
        }
        return false
    }

    if (!legacyIsFile) return false

    if (!fs.existsSync(CAPS_DIR)) fs.mkdirSync(CAPS_DIR, { recursive: true })
    fs.renameSync(LEGACY_CAPS_FILE, CAPS_FILE)
    logger.info('Moved validator capability config to ' + CAPS_FILE
        + ' (its own directory, so the hub mount cannot break `docker cp`).')
    return true
}

/**
 * Refuse to mount CAPS_DIR if it holds anything but the capability config.
 *
 * The whole directory goes into the hub container, so an extra file here is an
 * unreviewed hand-off to the hub; signing.key landing here would put the
 * validator's PRIVATE KEY in the container. Throwing fails the install loudly:
 * a silent skip would boot a hub with no capability config at all.
 */
function assertCapsDirIsolated() {
    const extra = fs.readdirSync(CAPS_DIR).filter(name => name !== CAPS_BASENAME)
    if (extra.length > 0) {
        throw new Error('refusing to mount ' + CAPS_DIR + ' into the hub container: it must contain only '
            + CAPS_BASENAME + ', found ' + extra.join(', ')
            + '. Move those files back under ' + VALIDATOR_DIR + ' (the signing key MUST NOT be in this directory).')
    }
}

// Point an existing capabilities.json at the DOGE wallet init just made,
// leaving every other operator edit alone. Only the two placeholder values
// are touched: a hand-set address is the operator's and stays.
function fillPublisherConfig(walletInfo) {
    if (!walletInfo || !walletInfo.dogeAddress || !isRegularFile(CAPS_FILE)) return false
    let caps
    try { caps = JSON.parse(fs.readFileSync(CAPS_FILE, 'utf8')) } catch { return false }
    const entry = caps.oracle_publish || (caps.oracle_publish = {})
    let changed = false
    if (!entry.doge_address || entry.doge_address === 'REPLACE_WITH_DOGE_ADDRESS') {
        entry.doge_address = walletInfo.dogeAddress; changed = true
    }
    if (!entry.doge_wallet || entry.doge_wallet === 'REPLACE_WITH_DOGE_WALLET_PATH') {
        entry.doge_wallet = SIGNER_CONTAINER_DIR + '/.env'; changed = true
    }
    if (changed) fs.writeFileSync(CAPS_FILE, JSON.stringify(caps, null, 2))
    return changed
}

function configureDependencies(dependencies) {
    ;({
        fs, crypto, NETWORK_BY_P2P_PORT, COIN_NETWORKS, SIGNER_CONTAINER_DIR,
        KEY_FILE, SETTINGS_FILE, CAPS_DIR, CAPS_FILE, LEGACY_CAPS_FILE,
        isRegularFile, VALIDATOR_DIR, CAPS_BASENAME, getLogger, logger
    } = dependencies)
}

module.exports = { resolveNetwork, PKCS8_ED25519_PREFIX, SPKI_ED25519_PREFIX, pubkeyFromSeedHex, defaultCapabilityConfig, isInitialized, ensureCapabilityConfigLayout, assertCapsDirIsolated, fillPublisherConfig, configureDependencies }
