/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 * XChain Node - Validator Service
 *
 * Validator-mode onboarding for the xchain-hub. `validator init` generates
 * an Ed25519 signing key and writes the validator config that install/start
 * inject into the hub container so it runs as a full validator (P2P + PBFT +
 * capability staking) instead of a standalone config oracle.
 *
 * Files (under configDir/validator/):
 *   signing.key                 64-hex Ed25519 seed (mode 0600): SIGNING_PRIVKEY_HEX
 *   validator.json              P2P + oracle settings + enabled flag + pubkey
 *   hub-caps/capabilities.json  HUB_CAPABILITY_CONFIG: MIN_STAKE thresholds +
 *                               self-test blocks
 *   wallets.env                 the two coin wallets (mode 0600): the BTC stake
 *                               wallet (funds fees, mints and holds the STAKE)
 *                               and the DOGE publisher wallet (pays for price
 *                               rounds and anchors). Generated by init, or
 *                               imported from operator-supplied WIFs.
 *   signer/signer.js + .env     the HUB_SIGNER_MODULE the hub loads to sign
 *                               DOGE publishes. Mounted read-only into the
 *                               container; the WIF stays in this directory.
 *
 * Both wallets are ordinary single-key P2PKH wallets, so an operator who wants
 * a branded (vanity) address generates the key elsewhere and imports the WIF:
 * `--import-stake-key` / `--import-doge-key` prompt for it with echo off, and
 * XCHAIN_NODE_STAKE_WIF / XCHAIN_NODE_DOGE_WIF carry it non-interactively.
 * Never as an argv value: a WIF in argv is a WIF in every process listing.
 *
 * The hub's API key is deliberately NOT one of these. A hub refuses to boot
 * without HUB_API_KEY unless keyless operation is declared, so a FRESH init
 * mints one, but it belongs to the HOST rather than to this validator identity:
 * the local indexer and the shared services authenticate to the same hub with
 * the same value. It therefore lives in the shared 0600 sidecar config/hub.local
 * alongside HUB_DB_PASS (ConfigService.ensureHubApiKey). A RE-RUN over an
 * already-initialized node only READS it (ConfigService.readHubApiKey): see
 * initValidator for why minting there breaks a keyless deployment.
 *
 * Why capabilities.json sits in its own `hub-caps/` subdirectory rather than
 * beside the other two: the hub container mounts it, and a SINGLE-FILE bind
 * mount breaks `docker cp` against that container forever. Docker's copy path
 * recreates every mount destination as a directory, so it hits the existing
 * file and aborts the whole operation with
 * "mkdirat validator/capabilities.json: file exists" - for ANY path copied,
 * not just the mounted one. Mounting a DIRECTORY instead has no such problem.
 * The directory that gets mounted must therefore contain the capability config
 * and NOTHING else: mounting `validator/` itself would put signing.key, the
 * validator's private key, inside the hub container. ensureCapabilityConfigLayout()
 * migrates pre-hub-caps installs, and assertCapsDirIsolated() refuses to build
 * the mount if anything else ever lands in that directory.
 *
 * The private key is never logged. Only the PUBLIC key is printed (operators
 * stake to it).
 ********************************************************************/

let fs = require('fs')
let crypto = require('crypto')
let { ensureHubApiKey, readHubApiKey } = require('../config_service')
let { COIN_NETWORKS, VALIDATOR_DIR, RELEASE_REF, KEY_FILE, SETTINGS_FILE, CAPS_DIR, CAPS_FILE, WALLETS_FILE, SIGNER_DIR, NETWORK_BY_P2P_PORT, P2P_PORT_BY_NETWORK, ORACLE_EPOCH_START_BY_NETWORK } = require('./validator_paths')
let { makeCoinWallet, resolveImportedWif, readWallets, writeWalletsFile, publicWalletInfo } = require('./wallets')
let { writeSignerDir } = require('./signer')
let { resolveNetwork, pubkeyFromSeedHex, defaultCapabilityConfig, isInitialized, ensureCapabilityConfigLayout, fillPublisherConfig } = require('./capability_layout')
let { getLogger } = require('../../observability/logger')
let logger = getLogger()

/**
 * Resolve the host's hub credential for this init run.
 *
 * A fresh install may GENERATE one (the hub refuses to boot in validator mode without it,
 * so an install that leaves none behind ends in a node that cannot start). A re-run over an
 * already-provisioned node may only READ, because minting one there is a silent outage:
 * see the refusal wording in reportHubApiKey. `--mint-hub-api-key` is the explicit opt-in
 * for the one case a re-run legitimately needs to generate, an old install that was
 * provisioned before init minted anything, leaving it unable to reach its hub.
 */
async function resolveHubApiKey(alreadyInitialized, opts) {
    if (!alreadyInitialized || opts.mintHubApiKey) {
        const key = await ensureHubApiKey()
        return { path: key.path, generated: key.generated, missing: false }
    }
    const key = await readHubApiKey()
    return { path: key.path, generated: false, missing: !key.present }
}

// One line of operator-facing output naming WHERE the hub credential lives, or the refusal
// and its consequence when there is none to name. The value is never printed: an API key in
// a terminal is an API key in a scrollback buffer.
function reportHubApiKey(hubApiKey) {
    if (hubApiKey.missing) {
        logger.info('  hub API key : NONE in ' + hubApiKey.path + ' - this host runs its hub KEYLESS,')
        logger.info('                and re-running init does NOT mint one. Every indexer, explorer and')
        logger.info('                service already pointed at this hub carries no key either, so a key')
        logger.info('                appearing here would flip the hub to authenticated on its next deploy')
        logger.info('                and 401 all of them at once, while the hub still reported healthy.')
        logger.info('                Re-run with --mint-hub-api-key ONLY if the hub is refusing to boot for')
        logger.info('                want of a key, and put the same value in every consumer before')
        logger.info('                redeploying the hub.')
        return
    }
    logger.info('  hub API key : ' + hubApiKey.path
        + ' (mode 0600, key HUB_API_KEY, ' + (hubApiKey.generated ? 'generated now' : 'already present, reused') + ')')
}

/**
 * Set up the two coin wallets and the DOGE signer, or report why not.
 *
 * Shared by a fresh init and by a re-run over an already-initialized
 * validator: a node initialized BEFORE wallets existed is exactly the node that
 * needs them, and making it rotate its signing key (and therefore re-stake, and
 * wait out the activation delay again) to get them would be a punishing upgrade
 * path for a working validator. Wallets are safe to repair on a re-run because
 * generating them affects nothing outside this node; the hub API key is not,
 * which is why that one only reads on a re-run (see initValidator).
 *
 * An existing wallets.env is KEPT unless --force-wallets: the signing key is
 * cheap to replace, but a funded stake or publisher address is not, and
 * regenerating it strands the coin.
 */
function setupWallets(network, opts) {
    const out = { wallets: readWallets(), generated: false, imported: [], skippedNoNetwork: false }
    if (opts.wallets === false) return out
    if (!network) {
        // A non-standard port is a custom federation, and a wallet is only
        // meaningful on a known coin network. Importing a key is an explicit
        // ask, so that case fails loud; plain init just says what it skipped.
        if (opts.importStakeKey || opts.importDogeKey || opts.forceWallets) {
            throw new Error('cannot set up wallets without knowing the network: pass --network testnet|mainnet, ' +
                'or --p2p-port 10002 (testnet) / 10001 (mainnet).')
        }
        out.skippedNoNetwork = true
        return out
    }
    if (out.wallets && !opts.forceWallets) return out

    const coins = COIN_NETWORKS[network]
    const stakeWif = resolveImportedWif('stake (BTC)', 'XCHAIN_NODE_STAKE_WIF', !!opts.importStakeKey)
    const dogeWif  = resolveImportedWif('DOGE publisher', 'XCHAIN_NODE_DOGE_WIF', !!opts.importDogeKey)
    const stake = makeCoinWallet(coins.stake, stakeWif)
    const doge  = makeCoinWallet(coins.doge, dogeWif)
    if (stakeWif) out.imported.push('stake')
    if (dogeWif)  out.imported.push('DOGE')
    writeWalletsFile(network, stake, doge)
    writeSignerDir(network, doge)
    out.wallets = readWallets() || {
        NETWORK: network, STAKE_ADDRESS: stake.address, STAKE_PUBKEY_HEX: stake.pubkeyHex,
        DOGE_ADDRESS: doge.address, DOGE_PUBKEY_HEX: doge.pubkeyHex
    }
    out.generated = true
    return out
}

// Print the two funding addresses. Addresses only: the keys stay in the file.
function reportWallets(walletInfo, network, verb) {
    const coins = COIN_NETWORKS[(walletInfo && walletInfo.network) || network] || COIN_NETWORKS.mainnet
    logger.info('  Wallets ' + verb + '. Fund these two addresses:')
    logger.info('    stake / fees   (' + coins.stakeCoin + ') : ' + walletInfo.stakeAddress)
    logger.info('    price + anchor (' + coins.dogeCoin  + ') : ' + walletInfo.dogeAddress)
}

function repairInitializedValidator(opts, hubApiKey) {
    const existing = JSON.parse(fs.readFileSync(SETTINGS_FILE, 'utf8'))
    logger.info('Validator already initialized. Pubkey: ' + existing.pubkey)
    reportHubApiKey(hubApiKey)

    // REPAIR, never rotate. Everything below is additive: it fills in what
    // a validator from an older version is missing and leaves the signing
    // key, and therefore the stake, alone.
    const network = resolveNetwork(opts, parseInt(opts.p2pPort) || existing.P2P_PORT || 0)
        || existing.network || NETWORK_BY_P2P_PORT[existing.P2P_PORT] || null

    // The hub refuses to boot in validator mode without HUB_NETWORK, and
    // getValidatorEnv can only supply it from a recorded network.
    if (!existing.network && network) {
        existing.network = network
        fs.writeFileSync(SETTINGS_FILE, JSON.stringify(existing, null, 2))
        logger.info('  network     : recorded as ' + network + ' (derived from P2P port ' + existing.P2P_PORT + ')')
    }

    const w = setupWallets(network, opts)
    const walletInfo = publicWalletInfo(w.wallets)
    if (w.generated) {
        ensureCapabilityConfigLayout()
        fillPublisherConfig(walletInfo)
    }
    logger.info('')
    if (walletInfo) {
        reportWallets(walletInfo, network, w.generated
            ? (w.imported.length ? 'imported (' + w.imported.join(', ') + ')' : 'generated now')
            : 'already present')
        if (w.generated) {
            logger.info('')
            logger.info('  Next: xchain-node validator stake      (dry run shows balances and the plan)')
        }
    } else if (w.skippedNoNetwork) {
        logger.info('  No wallets, and the network is unknown for port ' + existing.P2P_PORT + '.')
        logger.info('  Re-run with --network testnet|mainnet to generate them.')
    }
    logger.info('')
    logger.info('Re-run with --force to regenerate the SIGNING KEY (that creates a NEW key; you would need to re-stake).')
    logger.info('Wallets are never replaced by --force; --force-wallets does that, abandoning the old addresses.')
    return existing
}

function prepareValidatorSettings(opts, pubkey) {
    const capabilities = String(opts.capabilities || 'price,cross_chain,oracle_publish,attestation')
        .split(',').map(s => s.trim()).filter(Boolean)
    let seedNodes = String(opts.seedNodes || '')
        .split(',').map(s => s.trim()).filter(Boolean)

    // --network names the federation; the P2P port follows it (or names it, for
    // callers who only passed a port). Neither given keeps the historical
    // mainnet default of 10001.
    const explicitNetwork = resolveNetwork(opts, parseInt(opts.p2pPort) || 0)
    const p2pPort = parseInt(opts.p2pPort)
        || (explicitNetwork && P2P_PORT_BY_NETWORK[explicitNetwork])
        || 10001
    const network = explicitNetwork || NETWORK_BY_P2P_PORT[p2pPort] || null

    // A validator with no seeds dials nobody and joins no gossip mesh, while
    // looking healthy. Default to the bootstrap set; --seed-nodes overrides.
    // The PORT selects the network, so a wrong port reaches the wrong federation.
    let seedNodesDefaulted = false
    if (seedNodes.length === 0 && (p2pPort === 10001 || p2pPort === 10002)) {
        seedNodes = ['01','02','03','04','05'].map(n => 'ws://validator' + n + '.xchain.io:' + p2pPort)
        seedNodesDefaulted = true
    }

    // Oracle round numbering anchor. MUST match across the federation, so a
    // known federation's value is the default and --oracle-epoch-start overrides.
    let oracleEpochStart = opts.oracleEpochStart ? parseInt(opts.oracleEpochStart) : null
    let oracleEpochDefaulted = false
    if (!oracleEpochStart && network && ORACLE_EPOCH_START_BY_NETWORK[network]) {
        oracleEpochStart = ORACLE_EPOCH_START_BY_NETWORK[network]
        oracleEpochDefaulted = true
    }

    const settings = {
        enabled:            true,
        pubkey:             pubkey,
        network:            network,
        P2P_VALIDATOR_ADDR: opts.p2pAddr || ('0.0.0.0:' + p2pPort),
        P2P_PORT:           p2pPort,
        SEED_NODES:         seedNodes,
        ORACLE_EPOCH_START: oracleEpochStart,
        capabilities:       capabilities
    }
    return { settings, capabilities, seedNodes, seedNodesDefaulted, oracleEpochStart, oracleEpochDefaulted, p2pPort, network }
}

function persistValidatorFiles(opts, seedHex, settings, capabilities, network) {
    // The two coin wallets and the DOGE signer (see setupWallets).
    const walletSetup = setupWallets(network, opts)
    const walletsGenerated = walletSetup.generated
    const walletsImported  = walletSetup.imported
    const walletsSkippedNoNetwork = walletSetup.skippedNoNetwork
    const walletInfo = publicWalletInfo(walletSetup.wallets)

    // Write the secret key first, locked down, and never echo it.
    fs.writeFileSync(KEY_FILE, seedHex, { mode: 0o600 })
    fs.chmodSync(KEY_FILE, 0o600)
    fs.writeFileSync(SETTINGS_FILE, JSON.stringify(settings, null, 2))
    if (!fs.existsSync(CAPS_FILE) || opts.force) {
        fs.writeFileSync(CAPS_FILE, JSON.stringify(defaultCapabilityConfig(capabilities, walletInfo), null, 2))
    } else if (walletsGenerated) {
        fillPublisherConfig(walletInfo)
    }
    return { walletsGenerated, walletsImported, walletsSkippedNoNetwork, walletInfo }
}

function reportValidatorInitialization(state) {
    const {
        hubApiKey, settings, pubkey, network, walletInfo, walletsGenerated,
        walletsImported, walletsSkippedNoNetwork, p2pPort, oracleEpochDefaulted,
        oracleEpochStart, seedNodes, seedNodesDefaulted
    } = state
    logger.info('')
    logger.info('Validator initialized' + (network ? ' for ' + network : '') + '.')
    logger.info('  signing key : ' + KEY_FILE + ' (mode 0600, keep this secret and back it up)')
    logger.info('  settings    : ' + SETTINGS_FILE)
    logger.info('  capabilities: ' + CAPS_FILE)
    reportHubApiKey(hubApiKey)
    if (walletInfo) {
        logger.info('  wallets     : ' + WALLETS_FILE + ' (mode 0600, holds both private keys: BACK IT UP)')
        logger.info('  DOGE signer : ' + SIGNER_DIR + ' (mounted read-only into the hub)')
    }
    logger.info('')
    logger.info('  PUBKEY (stake XCHAIN to this to qualify capabilities):')
    logger.info('    ' + pubkey)
    logger.info('')
    if (walletInfo) {
        reportWallets(walletInfo, network, walletsGenerated
            ? (walletsImported.length ? 'imported (' + walletsImported.join(', ') + ')' : 'generated')
            : 'already present, kept')
        logger.info('')
        logger.info('  Then: xchain-node validator stake            (mints XCHAIN on testnet, then stakes)')
        logger.info('        xchain-node install ' + RELEASE_REF + ' xchain-hub  (starts the validator)')
    } else if (walletsSkippedNoNetwork) {
        logger.info('  Wallets skipped: the network is unknown for port ' + p2pPort + '. Re-run with --network testnet|mainnet')
        logger.info('  to generate them, or run your own signer via XCHAIN_NODE_HUB_SIGNER_DIR.')
    } else {
        logger.info('  Wallets skipped (--no-wallets). Run your own signer via XCHAIN_NODE_HUB_SIGNER_DIR')
        logger.info('  and set oracle_publish.doge_address in ' + CAPS_FILE + ' by hand.')
        logger.info('  Then: xchain-node install ' + RELEASE_REF + ' xchain-hub')
    }
    logger.info('')
    if (!settings.ORACLE_EPOCH_START)
        logger.info('  NOTE: set ORACLE_EPOCH_START (--oracle-epoch-start <unix-ms>) to the value shared by your federation before running the oracle.')
    else if (oracleEpochDefaulted)
        logger.info('  ORACLE_EPOCH_START: defaulted to the ' + network + ' federation value ' + oracleEpochStart + '.')
    if (seedNodes.length === 0)
        logger.info('  NOTE: no SEED_NODES set. Add peer addresses (--seed-nodes host:port,...) to join the gossip mesh.')
    else if (seedNodesDefaulted)
        logger.info('  SEED_NODES: defaulted to the five validator01-05.xchain.io bootstrap peers on port ' +
                    p2pPort + '. Override with --seed-nodes host:port,... if you peer elsewhere.')
    if (!network)
        logger.info('  NOTE: network unknown (non-standard port). The hub needs HUB_NETWORK in the host .env.')
    logger.info('  cross_chain needs a BTC RPC endpoint in ' + CAPS_FILE + ' or must be listed under DISABLED_CAPABILITIES.')
    logger.info('')
}

// Generate a key + write all validator files. Idempotent guard via `force`.
async function initValidator(opts = {}) {
    // A validator-mode hub REFUSES TO BOOT with no HUB_API_KEY, so a FRESH init has to
    // leave one behind or this whole ceremony ends in a node that cannot start.
    //
    // A RE-RUN over an already-provisioned node must NOT mint one, however it got here
    // (plain re-run or --force). A hub deployed with no key runs keyless
    // (HUB_ALLOW_UNAUTHENTICATED), and every indexer, explorer and shared service pointed
    // at it carries no key either; a key appearing in the sidecar flips the hub to
    // authenticated on its next deploy and 401s all of them at once. Measured on a regtest
    // host: three indexers dropped off the hub-db sync socket while the visible symptom
    // named none of it (a mirror-barrier timeout, hub healthy). So the re-run path reads
    // and reports, and says out loud what minting would cost; --mint-hub-api-key is the
    // explicit opt-in for the old install that really is stuck at a refused hub boot.
    const alreadyInitialized = isInitialized()
    const hubApiKey = await resolveHubApiKey(alreadyInitialized, opts)


    if (alreadyInitialized && !opts.force) return repairInitializedValidator(opts, hubApiKey)

    if (!fs.existsSync(VALIDATOR_DIR)) fs.mkdirSync(VALIDATOR_DIR, { recursive: true })
    if (!fs.existsSync(CAPS_DIR)) fs.mkdirSync(CAPS_DIR, { recursive: true })
    // An init over a pre-hub-caps install must adopt that install's tuned
    // config, not silently start beside it.
    ensureCapabilityConfigLayout()

    const seedHex = crypto.randomBytes(32).toString('hex')
    const pubkey  = pubkeyFromSeedHex(seedHex)

    const prepared = prepareValidatorSettings(opts, pubkey)
    const { settings, capabilities, network } = prepared
    const walletState = persistValidatorFiles(opts, seedHex, settings, capabilities, network)
    reportValidatorInitialization({ hubApiKey, pubkey, ...prepared, ...walletState })
    return settings
}

function configureDependencies(dependencies) {
    ;({
        fs, crypto, ensureHubApiKey, readHubApiKey, COIN_NETWORKS, VALIDATOR_DIR,
        RELEASE_REF, KEY_FILE, SETTINGS_FILE, CAPS_DIR, CAPS_FILE, WALLETS_FILE,
        SIGNER_DIR, NETWORK_BY_P2P_PORT, P2P_PORT_BY_NETWORK,
        ORACLE_EPOCH_START_BY_NETWORK, makeCoinWallet, resolveImportedWif,
        readWallets, writeWalletsFile, publicWalletInfo, writeSignerDir,
        resolveNetwork, pubkeyFromSeedHex, defaultCapabilityConfig, isInitialized,
        ensureCapabilityConfigLayout, fillPublisherConfig, getLogger, logger
    } = dependencies)
}

module.exports = { resolveHubApiKey, reportHubApiKey, setupWallets, reportWallets, initValidator, configureDependencies }
