/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 * XChain Node - Validator Service
 *
 * Validator-mode onboarding for the xchain-hub. `validator init` generates
 * an Ed25519 signing key and writes the validator config that install/start
 * inject into the hub container so it runs as a full validator (P2P + PBFT +
 * capability staking) instead of a standalone config oracle.
 *
 * Files (under configDir/validator/):
 *   signing.key                 64-hex Ed25519 seed (mode 0600): SIGNING_PRIVKEY_HEX
 *   validator.json              P2P + oracle settings + enabled flag + pubkey
 *   hub-caps/capabilities.json  HUB_CAPABILITY_CONFIG: MIN_STAKE thresholds +
 *                               self-test blocks
 *   wallets.env                 the two coin wallets (mode 0600): the BTC stake
 *                               wallet (funds fees, mints and holds the STAKE)
 *                               and the DOGE publisher wallet (pays for price
 *                               rounds and anchors). Generated by init, or
 *                               imported from operator-supplied WIFs.
 *   signer/signer.js + .env     the HUB_SIGNER_MODULE the hub loads to sign
 *                               DOGE publishes. Mounted read-only into the
 *                               container; the WIF stays in this directory.
 *
 * Both wallets are ordinary single-key P2PKH wallets, so an operator who wants
 * a branded (vanity) address generates the key elsewhere and imports the WIF:
 * `--import-stake-key` / `--import-doge-key` prompt for it with echo off, and
 * XCHAIN_NODE_STAKE_WIF / XCHAIN_NODE_DOGE_WIF carry it non-interactively.
 * Never as an argv value: a WIF in argv is a WIF in every process listing.
 *
 * The hub's API key is deliberately NOT one of these. A hub refuses to boot
 * without HUB_API_KEY unless keyless operation is declared, so a FRESH init
 * mints one, but it belongs to the HOST rather than to this validator identity:
 * the local indexer and the shared services authenticate to the same hub with
 * the same value. It therefore lives in the shared 0600 sidecar config/hub.local
 * alongside HUB_DB_PASS (ConfigService.ensureHubApiKey). A RE-RUN over an
 * already-initialized node only READS it (ConfigService.readHubApiKey): see
 * initValidator for why minting there breaks a keyless deployment.
 *
 * Why capabilities.json sits in its own `hub-caps/` subdirectory rather than
 * beside the other two: the hub container mounts it, and a SINGLE-FILE bind
 * mount breaks `docker cp` against that container forever. Docker's copy path
 * recreates every mount destination as a directory, so it hits the existing
 * file and aborts the whole operation with
 * "mkdirat validator/capabilities.json: file exists" - for ANY path copied,
 * not just the mounted one. Mounting a DIRECTORY instead has no such problem.
 * The directory that gets mounted must therefore contain the capability config
 * and NOTHING else: mounting `validator/` itself would put signing.key, the
 * validator's private key, inside the hub container. ensureCapabilityConfigLayout()
 * migrates pre-hub-caps installs, and assertCapsDirIsolated() refuses to build
 * the mount if anything else ever lands in that directory.
 *
 * The private key is never logged. Only the PUBLIC key is printed (operators
 * stake to it).
 ********************************************************************/

let { COIN_NETWORKS } = require('./validator_paths')
let { loadSdk } = require('./wallets')
let { getActiveSignerFile, signerModuleExportsBroadcast } = require('./signer')

// ROLLCALL: every epoch (1008 BTC blocks, 30 on regtest) each validator signs
// a message over that epoch's ledger_hash; the elected leader publishes the
// collected signatures on DOGE, and the BTC indexer closes the epoch and
// evicts a staking source absent for K=2 consecutive rolled epochs. Every
// ROLLCALL payload exceeds the 76-byte OP_RETURN cap, so it always rides the
// chunked two-phase P2SH lane - two transactions, ~0.003 DOGE each - which is
// where the per-call DOGE cost below comes from. It spends from the same
// publisher wallet anchors already use; no separate wallet or key.
const ROLLCALL_DOGE_COST_PER_CALL = 0.006
// BTC blocks per ROLLCALL epoch, network-keyed. An absence read only ever
// returns absent epochs, so two rows are a true back-to-back streak only when
// their epoch_height values are exactly one epoch apart; any other gap means
// a rolled (present) epoch fell between them, however close the rows sit in
// the array.
const ROLLCALL_EPOCH_BLOCKS = { regtest: 30, testnet: 1008, mainnet: 1008 }
const ROLLCALL_EPOCH_BLOCKS_DEFAULT = 1008

function rollcallEpochBlocks(network) {
    return ROLLCALL_EPOCH_BLOCKS[network] || ROLLCALL_EPOCH_BLOCKS_DEFAULT
}

// Count the consecutive absences from the HEAD of an epoch_height-DESC
// absence list (the read is ordered that way; see getRollcallStatus). The
// read only ever returns absent epochs, so two rows are truly back-to-back
// in time only when they are exactly one epoch's worth of blocks apart;
// anything else means a rolled (present) epoch fell between them and the
// streak broke there, no matter how close together the two rows sit in the
// array. Only the run starting at index 0 counts - an old streak buried
// deeper in the history is not this key's CURRENT exposure.
function rollcallAbsenceStreak(absences, epochBlocks) {
    const rows = Array.isArray(absences) ? absences : []
    if (!rows.length) return 0
    let streak = 1
    for (let i = 1; i < rows.length; i++) {
        const gap = Number(rows[i - 1].epoch_height) - Number(rows[i].epoch_height)
        if (gap !== epochBlocks) break
        streak++
    }
    return streak
}

/**
 * Everything `validator status` needs to report ROLLCALL health, gathered in
 * one pass:
 *   - the DOGE publisher's roll-call runway, from the SAME balance read
 *     anchors already report (never a second fetch);
 *   - whether the configured signer can PUBLISH a roll call rather than only
 *     sign one (the trap: every ROLLCALL payload exceeds the 76-byte
 *     OP_RETURN cap, so it always needs the chunked two-phase P2SH lane, and
 *     the hub's built-in broadcast pipeline only finishes phase 1 there);
 *   - this key's BTC-side absence streak, read from the indexer's public
 *     getrollcallabsences({source, limit}) -> {absences: [...]}.
 *
 * Each of the three degrades independently to an "unavailable" shape rather
 * than throwing: one read failing (an unreachable indexer, an older indexer
 * without this read yet) must not hide the other two, and must never read as
 * a reassuring zero.
 *
 * `deps.makeSdk(sdkNetwork)` lets tests inject a fake SDK without touching the
 * network, the same shape ValidatorStakeService's tests already use.
 */
async function getRollcallStatus(walletInfo, network, deps = {}) {
    const coins = COIN_NETWORKS[network] || null
    const out = { doge: null, broadcast: null, absences: null }

    const signerFile = deps.getActiveSignerFile ? deps.getActiveSignerFile() : getActiveSignerFile()
    if (signerFile) out.broadcast = { file: signerFile, exportsBroadcast: signerModuleExportsBroadcast(signerFile) }

    if (!walletInfo || !coins) return out

    const { XChainSDK } = deps.sdk || loadSdk()
    const makeSdk = deps.makeSdk || (sdkNetwork => new XChainSDK({ network: sdkNetwork }))

    if (walletInfo.dogeAddress) {
        try {
            const dogeSdk = makeSdk(coins.doge)
            const addr = await dogeSdk.explorer.getAddress(walletInfo.dogeAddress)
            const balance = Number(addr && addr.balances && addr.balances.confirmed)
            const safeBalance = Number.isFinite(balance) ? balance : 0
            out.doge = {
                unavailable: false,
                balance: safeBalance,
                rollcalls: Math.floor(safeBalance / ROLLCALL_DOGE_COST_PER_CALL)
            }
        } catch (e) {
            out.doge = { unavailable: true, error: e.message }
        }
    }

    if (walletInfo.stakeAddress) {
        try {
            const btcSdk = makeSdk(coins.stake)
            if (typeof btcSdk.explorer.getRollcallAbsences !== 'function') {
                // Older indexer: the read is not there yet, not "no absences".
                out.absences = { unavailable: true, reason: 'this indexer does not expose roll-call absence reads yet' }
            } else {
                const r = await btcSdk.explorer.getRollcallAbsences({ source: walletInfo.stakeAddress, limit: 20 })
                const rows = (r && Array.isArray(r.absences)) ? r.absences : []
                out.absences = {
                    unavailable: false,
                    streak: rollcallAbsenceStreak(rows, rollcallEpochBlocks(network)),
                    // The chain's own flag on the most recent absence, read directly
                    // rather than re-derived from the streak count, since it is the
                    // authoritative answer to "did THIS absence complete the K=2 run".
                    evictedNow: rows.length > 0 && Number(rows[0].evicted) === 1
                }
            }
        } catch (e) {
            out.absences = { unavailable: true, error: e.message }
        }
    }

    return out
}

function configureDependencies(dependencies) {
    ;({ COIN_NETWORKS, loadSdk, getActiveSignerFile, signerModuleExportsBroadcast } = dependencies)
}

module.exports = { ROLLCALL_DOGE_COST_PER_CALL, ROLLCALL_EPOCH_BLOCKS, ROLLCALL_EPOCH_BLOCKS_DEFAULT, rollcallEpochBlocks, rollcallAbsenceStreak, getRollcallStatus, configureDependencies }
