/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 * XChain Node - Validator Service
 *
 * Validator-mode onboarding for the xchain-hub. `validator init` generates
 * an Ed25519 signing key and writes the validator config that install/start
 * inject into the hub container so it runs as a full validator (P2P + PBFT +
 * capability staking) instead of a standalone config oracle.
 *
 * Files (under configDir/validator/):
 *   signing.key                 64-hex Ed25519 seed (mode 0600): SIGNING_PRIVKEY_HEX
 *   validator.json              P2P + oracle settings + enabled flag + pubkey
 *   hub-caps/capabilities.json  HUB_CAPABILITY_CONFIG: MIN_STAKE thresholds +
 *                               self-test blocks
 *   wallets.env                 the two coin wallets (mode 0600): the BTC stake
 *                               wallet (funds fees, mints and holds the STAKE)
 *                               and the DOGE publisher wallet (pays for price
 *                               rounds and anchors). Generated by init, or
 *                               imported from operator-supplied WIFs.
 *   signer/signer.js + .env     the HUB_SIGNER_MODULE the hub loads to sign
 *                               DOGE publishes. Mounted read-only into the
 *                               container; the WIF stays in this directory.
 *
 * Both wallets are ordinary single-key P2PKH wallets, so an operator who wants
 * a branded (vanity) address generates the key elsewhere and imports the WIF:
 * `--import-stake-key` / `--import-doge-key` prompt for it with echo off, and
 * XCHAIN_NODE_STAKE_WIF / XCHAIN_NODE_DOGE_WIF carry it non-interactively.
 * Never as an argv value: a WIF in argv is a WIF in every process listing.
 *
 * The hub's API key is deliberately NOT one of these. A hub refuses to boot
 * without HUB_API_KEY unless keyless operation is declared, so a FRESH init
 * mints one, but it belongs to the HOST rather than to this validator identity:
 * the local indexer and the shared services authenticate to the same hub with
 * the same value. It therefore lives in the shared 0600 sidecar config/hub.local
 * alongside HUB_DB_PASS (ConfigService.ensureHubApiKey). A RE-RUN over an
 * already-initialized node only READS it (ConfigService.readHubApiKey): see
 * initValidator for why minting there breaks a keyless deployment.
 *
 * Why capabilities.json sits in its own `hub-caps/` subdirectory rather than
 * beside the other two: the hub container mounts it, and a SINGLE-FILE bind
 * mount breaks `docker cp` against that container forever. Docker's copy path
 * recreates every mount destination as a directory, so it hits the existing
 * file and aborts the whole operation with
 * "mkdirat validator/capabilities.json: file exists" - for ANY path copied,
 * not just the mounted one. Mounting a DIRECTORY instead has no such problem.
 * The directory that gets mounted must therefore contain the capability config
 * and NOTHING else: mounting `validator/` itself would put signing.key, the
 * validator's private key, inside the hub container. ensureCapabilityConfigLayout()
 * migrates pre-hub-caps installs, and assertCapsDirIsolated() refuses to build
 * the mount if anything else ever lands in that directory.
 *
 * The private key is never logged. Only the PUBLIC key is printed (operators
 * stake to it).
 ********************************************************************/

let fs = require('fs')
let path = require('path')
let config = require('../../config')
let {
    SIGNER_DIR, SIGNER_FILE, SIGNER_ENV_FILE, COIN_NETWORKS,
    PUBLIC_ENCODER_BASE, isRegularFile, SIGNER_MODULES_DIR
} = require('./validator_paths')

// The HUB_SIGNER_MODULE the hub loads. Same contract as xchain-hub's
// examples/doge-signer.example.js (walletSign + the two-phase broadcast); kept
// here as a template so init works offline and the operator has one file to
// read if they want to replace it with their own signer.
const SIGNER_TEMPLATE = `/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 **********************************************************************
 *
 * HUB_SIGNER_MODULE written by \`xchain-node validator init\`.
 *
 * The hub's on-chain publishers (PRICE rounds, ANCHOR checkpoints) hand this
 * module a raw wire payload. It funds and reveals the two-phase P2SH encoding
 * through the encoder named in .env, signing with the DOGE publisher key that
 * lives beside this file. The key never enters the hub container's
 * environment: this directory is mounted read-only and only this module
 * reads it.
 *
 * Replace this file with your own signer if you keep keys elsewhere (an HSM,
 * a hardware wallet, a remote signing service). The contract is:
 *   walletSign(psbtHex) -> Promise<txHex>   REQUIRED
 *   broadcast(payload)  -> Promise<{txid}>  optional, replaces the default pipeline
 *   getBalance()        -> Promise<number>  optional, low-balance warnings
 *
 ********************************************************************/

const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const { XChainSDK } = require('@dankest-llc/xchain-sdk');

const NETWORK    = process.env.DOGE_NETWORK || '';
const WIF        = process.env.DOGE_WIF || '';
const ADDRESS    = process.env.DOGE_ADDRESS || '';
const ENCODER    = process.env.DOGE_ENCODER_URL || '';
const FEE_PER_KB = process.env.DOGE_FEE_PER_KB ? Number(process.env.DOGE_FEE_PER_KB) : undefined;

// Fail at load time: the hub treats a configured-but-broken signer as fatal,
// and a signer that cannot sign must not boot quietly.
for (const [name, value] of [['DOGE_NETWORK', NETWORK], ['DOGE_WIF', WIF], ['DOGE_ADDRESS', ADDRESS], ['DOGE_ENCODER_URL', ENCODER]]) {
    if (!value) throw new Error('doge-signer: ' + name + ' is not set in ' + path.join(__dirname, '.env'));
}

const sdk = new XChainSDK({ network: NETWORK, encoderUrl: ENCODER });

module.exports = {
    // Full publish pipeline for a raw wire payload string -> { txid }. The
    // returned txid is the phase-2 (reveal) txid when two-phase encoding is
    // used; that is the transaction indexers decode.
    async broadcast(payload) {
        const encoder = sdk.requireEncoder();

        const txParams = { data: payload, pubkey: ADDRESS, change: ADDRESS, encoding: 'P2SH' };
        if (FEE_PER_KB !== undefined) txParams.feePerKb = FEE_PER_KB;

        const encoded = await encoder.createTx(txParams);
        const signed  = sdk.wallet.signPsbt(encoded.psbt, WIF);
        await encoder.broadcastTx(signed.txHex);
        if (encoded.encoding !== 'P2SH' && encoded.encoding !== 'P2WSH')
            return { txid: signed.txid };

        // Phase 1 has funded the P2SH outputs on chain, so every failure below is a
        // POST-SPEND failure and has to say so on the way out. The hub reads a
        // definitive encoder rejection as safe to retry, and a retry re-enters this
        // function, runs createTx over fresh UTXOs and funds the same payload a second
        // time. fundsCommitted makes the hub fail closed instead; phase1Txid is what an
        // operator reconciles the stranded funding transaction against.
        try {
            const spendParams = {
                pubkey:   ADDRESS,
                p2shHash: signed.txid,
                p2shHex:  signed.txHex,
                data:     payload,
                encoding: encoded.encoding,
                change:   ADDRESS
            };
            if (FEE_PER_KB !== undefined) spendParams.feePerKb = FEE_PER_KB;
            const spendResult = await encoder.spendP2sh(spendParams);
            const spendSigned = sdk.wallet.signRevealPsbt(spendResult.psbt, WIF);
            await encoder.broadcastTx(spendSigned.txHex);

            return { txid: spendSigned.txid, phase1_txid: signed.txid };
        } catch (err) {
            // Mutate and rethrow the SAME object where there is one: the classifier
            // reads err.response and err.message off the original, and a fresh wrapper
            // would drop both. A thrown non-object gets a carrier instead.
            const tagged = (err && typeof err === 'object')
                ? err
                : new Error('doge-signer: phase 2 failed after funding: ' + String(err));
            tagged.fundsCommitted = true;
            tagged.phase1Txid     = signed.txid;
            throw tagged;
        }
    },

    // Sign an encoder-built PSBT -> signed raw tx hex. The hub's built-in
    // phase-1 pipeline and balance plumbing use this; broadcast() above takes
    // precedence when both are exported.
    async walletSign(psbtHex) {
        return sdk.wallet.signPsbt(psbtHex, WIF).txHex;
    }
};
`

function writeSignerDir(network, doge) {
    if (!fs.existsSync(SIGNER_DIR)) fs.mkdirSync(SIGNER_DIR, { recursive: true })
    ensureSignerModulesMountpoint()
    const coins = COIN_NETWORKS[network]
    fs.writeFileSync(SIGNER_FILE, SIGNER_TEMPLATE, { mode: 0o644 })
    const env = [
        '# DOGE publisher signer config, written by `xchain-node validator init`. Mode 0600.',
        '# DOGE_ENCODER_URL: the encoder that builds and relays the DOGE transactions.',
        '# The public XChain encoder is the default; point it at your own if you run one.',
        'DOGE_NETWORK=' + coins.doge,
        'DOGE_ADDRESS=' + doge.address,
        'DOGE_ENCODER_URL=' + (config.DOGE_ENCODER_URL || (PUBLIC_ENCODER_BASE + coins.dogeCoin)),
        'DOGE_WIF=' + doge.wif,
        ''
    ].join('\n')
    fs.writeFileSync(SIGNER_ENV_FILE, env, { mode: 0o600 })
    fs.chmodSync(SIGNER_ENV_FILE, 0o600)
}

function signerDirExists() {
    return isRegularFile(SIGNER_FILE) && isRegularFile(SIGNER_ENV_FILE)
}

// Create the empty node_modules directory the SDK mount lands on (see
// SIGNER_MODULES_DIR). Idempotent, and re-checked at mount time rather than
// only at init, so a config directory written before this existed still starts.
// An empty node_modules on the host is harmless outside the container: node
// keeps walking up the tree when a package is not found in it.
function ensureSignerModulesMountpoint() {
    if (!fs.existsSync(SIGNER_MODULES_DIR)) fs.mkdirSync(SIGNER_MODULES_DIR, { recursive: true })
}

// Host directory to mount at SIGNER_CONTAINER_DIR, or null. An operator who
// set XCHAIN_NODE_HUB_SIGNER_DIR runs their own signer and wins; the generated
// one is the default for everyone else. The signer requires the SDK, which is
// resolved from a node_modules mounted BESIDE it (ModuleService mounts this
// package's own node_modules there), so init never has to run npm.
function getSignerMountDir() {
    if (config.XCHAIN_NODE_HUB_SIGNER_DIR) return null
    if (!signerDirExists()) return null
    ensureSignerModulesMountpoint()
    return SIGNER_DIR
}

// The signer.js file actually in force: an operator-supplied module wins
// (same precedence as getSignerMountDir), or the generated module after
// init writes it. Null when neither is configured. Used for the roll-call
// broadcast check below, which reads this path rather than the mount dir.
function getActiveSignerFile() {
    if (config.XCHAIN_NODE_HUB_SIGNER_DIR) return path.join(config.XCHAIN_NODE_HUB_SIGNER_DIR, 'signer.js')
    return signerDirExists() ? SIGNER_FILE : null
}

// Strip comments before scanning a signer module's source, so a doc comment
// that merely mentions `broadcast(...)` (the generated template's own
// contract comment does exactly that, right above its module.exports) cannot
// be mistaken for the export itself.
function stripJsComments(src) {
    return String(src || '').replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '')
}

// Whether a signer module's module.exports names a `broadcast` export. Static
// only: this CLI never requires an operator-supplied signer file just to ask
// it a question, because that module's top-level code is meant to run inside
// the hub container (with its own env, its own SDK session) - not at
// `validator status` time, under whatever privileges ran the CLI. Returns
// null when there is no file to check.
function signerModuleExportsBroadcast(signerFilePath) {
    if (!signerFilePath || !isRegularFile(signerFilePath)) return null
    let src
    try { src = fs.readFileSync(signerFilePath, 'utf8') } catch { return null }
    const stripped = stripJsComments(src)
    if (/\bexports\.broadcast\s*=/.test(stripped)) return true
    // Scope the object-literal form (`broadcast(payload) {...}` or
    // `broadcast: ...` inside `module.exports = { ... }`) to text from the
    // LAST module.exports onward, so a `broadcast` named only in prose or a
    // helper earlier in the file cannot false-positive.
    const idx = stripped.lastIndexOf('module.exports')
    const tail = idx >= 0 ? stripped.slice(idx) : ''
    return /\bbroadcast\s*(?:\(|:)/.test(tail)
}

function configureDependencies(dependencies) {
    ;({
        fs, path, config, SIGNER_DIR, SIGNER_FILE, SIGNER_ENV_FILE,
        COIN_NETWORKS, PUBLIC_ENCODER_BASE, isRegularFile, SIGNER_MODULES_DIR
    } = dependencies)
}

module.exports = { SIGNER_TEMPLATE, writeSignerDir, signerDirExists, ensureSignerModulesMountpoint, getSignerMountDir, getActiveSignerFile, stripJsComments, signerModuleExportsBroadcast, configureDependencies }
