/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 * XChain Node - Validator Service
 *
 * Validator-mode onboarding for the xchain-hub. `validator init` generates
 * an Ed25519 signing key and writes the validator config that install/start
 * inject into the hub container so it runs as a full validator (P2P + PBFT +
 * capability staking) instead of a standalone config oracle.
 *
 * Files (under configDir/validator/):
 *   signing.key                 64-hex Ed25519 seed (mode 0600): SIGNING_PRIVKEY_HEX
 *   validator.json              P2P + oracle settings + enabled flag + pubkey
 *   hub-caps/capabilities.json  HUB_CAPABILITY_CONFIG: MIN_STAKE thresholds +
 *                               self-test blocks
 *   wallets.env                 the two coin wallets (mode 0600): the BTC stake
 *                               wallet (funds fees, mints and holds the STAKE)
 *                               and the DOGE publisher wallet (pays for price
 *                               rounds and anchors). Generated by init, or
 *                               imported from operator-supplied WIFs.
 *   signer/signer.js + .env     the HUB_SIGNER_MODULE the hub loads to sign
 *                               DOGE publishes. Mounted read-only into the
 *                               container; the WIF stays in this directory.
 *
 * Both wallets are ordinary single-key P2PKH wallets, so an operator who wants
 * a branded (vanity) address generates the key elsewhere and imports the WIF:
 * `--import-stake-key` / `--import-doge-key` prompt for it with echo off, and
 * XCHAIN_NODE_STAKE_WIF / XCHAIN_NODE_DOGE_WIF carry it non-interactively.
 * Never as an argv value: a WIF in argv is a WIF in every process listing.
 *
 * The hub's API key is deliberately NOT one of these. A hub refuses to boot
 * without HUB_API_KEY unless keyless operation is declared, so a FRESH init
 * mints one, but it belongs to the HOST rather than to this validator identity:
 * the local indexer and the shared services authenticate to the same hub with
 * the same value. It therefore lives in the shared 0600 sidecar config/hub.local
 * alongside HUB_DB_PASS (ConfigService.ensureHubApiKey). A RE-RUN over an
 * already-initialized node only READS it (ConfigService.readHubApiKey): see
 * initValidator for why minting there breaks a keyless deployment.
 *
 * Why capabilities.json sits in its own `hub-caps/` subdirectory rather than
 * beside the other two: the hub container mounts it, and a SINGLE-FILE bind
 * mount breaks `docker cp` against that container forever. Docker's copy path
 * recreates every mount destination as a directory, so it hits the existing
 * file and aborts the whole operation with
 * "mkdirat validator/capabilities.json: file exists" - for ANY path copied,
 * not just the mounted one. Mounting a DIRECTORY instead has no such problem.
 * The directory that gets mounted must therefore contain the capability config
 * and NOTHING else: mounting `validator/` itself would put signing.key, the
 * validator's private key, inside the hub container. ensureCapabilityConfigLayout()
 * migrates pre-hub-caps installs, and assertCapsDirIsolated() refuses to build
 * the mount if anything else ever lands in that directory.
 *
 * The private key is never logged. Only the PUBLIC key is printed (operators
 * stake to it).
 ********************************************************************/

let fs = require('fs')
let config = require('../../config')
let {
    SETTINGS_FILE, KEY_FILE, CAPS_CONTAINER_PATH, SIGNER_CONTAINER_PATH,
    COIN_NETWORKS, PUBLIC_ENCODER_BASE, VALIDATOR_DIR, CAPS_FILE, isRegularFile, CAPS_DIR
} = require('./validator_paths')
let { isInitialized, ensureCapabilityConfigLayout, assertCapsDirIsolated } = require('./capability_layout')
let { readWallets, publicWalletInfo } = require('./wallets')
let { getSignerMountDir } = require('./signer')

// Read persisted validator settings (or null if not initialized / disabled).
function getValidatorSettings() {
    if (!isInitialized()) return null
    try {
        const s = JSON.parse(fs.readFileSync(SETTINGS_FILE, 'utf8'))
        return s && s.enabled ? s : null
    } catch { return null }
}

// Build the env-var fragment injected into the hub container when validator
// mode is enabled. Returns {} for standalone (no validator configured), so the
// standalone install is byte-for-byte unchanged.
function getValidatorEnv() {
    const s = getValidatorSettings()
    if (!s) return {}
    const env = {
        P2P_VALIDATOR_ADDR: s.P2P_VALIDATOR_ADDR,
        P2P_PORT:           s.P2P_PORT,
        SEED_NODES:         (s.SEED_NODES || []).join(','),
        SIGNING_PRIVKEY_HEX: fs.readFileSync(KEY_FILE, 'utf8').trim(),
        HUB_CAPABILITY_CONFIG: CAPS_CONTAINER_PATH
    }
    if (s.ORACLE_EPOCH_START) env.ORACLE_EPOCH_START = s.ORACLE_EPOCH_START

    // The hub refuses to boot in validator mode without HUB_NETWORK. Host env
    // wins (the passthrough list already copied it); the recorded network
    // fills the gap so a fresh install needs no .env edit for it.
    if (!config.HUB_NETWORK && s.network) env.HUB_NETWORK = s.network

    // DOGE publisher wiring, from the wallet init made. Every value here is
    // public (address, pubkey, encoder URL); the WIF stays in the mounted
    // signer directory. Host env wins on each, so an operator running their
    // own publisher is not overridden.
    const w = publicWalletInfo(readWallets())
    if (w && w.dogeAddress) {
        const coins = COIN_NETWORKS[w.network || s.network] || null
        env.DOGE_ADDRESS    = config.DOGE_ADDRESS    || w.dogeAddress
        env.DOGE_PUBKEY_HEX = config.DOGE_PUBKEY_HEX || w.dogePubkeyHex
        env.DOGE_ENCODER_URL = config.DOGE_ENCODER_URL
            || (coins ? PUBLIC_ENCODER_BASE + coins.dogeCoin : '')
        if (!env.DOGE_ENCODER_URL) delete env.DOGE_ENCODER_URL
    }
    if (getSignerMountDir()) env.HUB_SIGNER_MODULE = SIGNER_CONTAINER_PATH
    return env
}

// Separate the three states getValidatorEnv() flattens into {}: standalone,
// disabled, and a configDir holding no validator/ for a host that has one. Report
// the directory too, because those last two are otherwise indistinguishable.
function validatorModeReport() {
    const settingsPresent = fs.existsSync(SETTINGS_FILE)
    const keyPresent      = fs.existsSync(KEY_FILE)
    if (settingsPresent && keyPresent) {
        return { mode: getValidatorSettings() ? 'validator' : 'disabled', dir: VALIDATOR_DIR, missing: [] }
    }
    // Half the pair is a broken install, never a standalone node.
    if (settingsPresent || keyPresent) {
        const missing = []
        if (!settingsPresent) missing.push(SETTINGS_FILE)
        if (!keyPresent) missing.push(KEY_FILE)
        return { mode: 'incomplete', dir: VALIDATOR_DIR, missing }
    }
    return { mode: 'standalone', dir: VALIDATOR_DIR, missing: [SETTINGS_FILE, KEY_FILE] }
}

// Host path of capabilities.json (the file the operator edits), or null.
// Migrates a legacy layout first, so this always names the file the hub reads.
function getCapabilityConfigHostPath() {
    if (!getValidatorSettings()) return null
    ensureCapabilityConfigLayout()
    return isRegularFile(CAPS_FILE) ? CAPS_FILE : null
}

// Host DIRECTORY to bind-mount into the hub container (or null when this node
// is not a validator / has no capability config yet). A directory, not the
// file: a single-file bind mount breaks `docker cp` against the container for
// every path, forever. Verified isolated before it is handed over.
function getCapabilityConfigMountDir() {
    if (!getCapabilityConfigHostPath()) return null
    assertCapsDirIsolated()
    return CAPS_DIR
}

function configureDependencies(dependencies) {
    ;({
        fs, config, SETTINGS_FILE, KEY_FILE, CAPS_CONTAINER_PATH,
        SIGNER_CONTAINER_PATH, COIN_NETWORKS, PUBLIC_ENCODER_BASE, VALIDATOR_DIR,
        CAPS_FILE, isRegularFile, CAPS_DIR, isInitialized,
        ensureCapabilityConfigLayout, assertCapsDirIsolated, readWallets,
        publicWalletInfo, getSignerMountDir
    } = dependencies)
}

module.exports = { getValidatorSettings, getValidatorEnv, validatorModeReport, getCapabilityConfigHostPath, getCapabilityConfigMountDir, configureDependencies }
