/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 * XChain Node - Validator Service
 *
 * Validator-mode onboarding for the xchain-hub. `validator init` generates
 * an Ed25519 signing key and writes the validator config that install/start
 * inject into the hub container so it runs as a full validator (P2P + PBFT +
 * capability staking) instead of a standalone config oracle.
 *
 * Files (under configDir/validator/):
 *   signing.key                 64-hex Ed25519 seed (mode 0600): SIGNING_PRIVKEY_HEX
 *   validator.json              P2P + oracle settings + enabled flag + pubkey
 *   hub-caps/capabilities.json  HUB_CAPABILITY_CONFIG: MIN_STAKE thresholds +
 *                               self-test blocks
 *   wallets.env                 the two coin wallets (mode 0600): the BTC stake
 *                               wallet (funds fees, mints and holds the STAKE)
 *                               and the DOGE publisher wallet (pays for price
 *                               rounds and anchors). Generated by init, or
 *                               imported from operator-supplied WIFs.
 *   signer/signer.js + .env     the HUB_SIGNER_MODULE the hub loads to sign
 *                               DOGE publishes. Mounted read-only into the
 *                               container; the WIF stays in this directory.
 *
 * Both wallets are ordinary single-key P2PKH wallets, so an operator who wants
 * a branded (vanity) address generates the key elsewhere and imports the WIF:
 * `--import-stake-key` / `--import-doge-key` prompt for it with echo off, and
 * XCHAIN_NODE_STAKE_WIF / XCHAIN_NODE_DOGE_WIF carry it non-interactively.
 * Never as an argv value: a WIF in argv is a WIF in every process listing.
 *
 * The hub's API key is deliberately NOT one of these. A hub refuses to boot
 * without HUB_API_KEY unless keyless operation is declared, so a FRESH init
 * mints one, but it belongs to the HOST rather than to this validator identity:
 * the local indexer and the shared services authenticate to the same hub with
 * the same value. It therefore lives in the shared 0600 sidecar config/hub.local
 * alongside HUB_DB_PASS (ConfigService.ensureHubApiKey). A RE-RUN over an
 * already-initialized node only READS it (ConfigService.readHubApiKey): see
 * initValidator for why minting there breaks a keyless deployment.
 *
 * Why capabilities.json sits in its own `hub-caps/` subdirectory rather than
 * beside the other two: the hub container mounts it, and a SINGLE-FILE bind
 * mount breaks `docker cp` against that container forever. Docker's copy path
 * recreates every mount destination as a directory, so it hits the existing
 * file and aborts the whole operation with
 * "mkdirat validator/capabilities.json: file exists" - for ANY path copied,
 * not just the mounted one. Mounting a DIRECTORY instead has no such problem.
 * The directory that gets mounted must therefore contain the capability config
 * and NOTHING else: mounting `validator/` itself would put signing.key, the
 * validator's private key, inside the hub container. ensureCapabilityConfigLayout()
 * migrates pre-hub-caps installs, and assertCapsDirIsolated() refuses to build
 * the mount if anything else ever lands in that directory.
 *
 * The private key is never logged. Only the PUBLIC key is printed (operators
 * stake to it).
 ********************************************************************/

let fs = require('fs')
let path = require('path')
let { configDir } = require('../../config')

let VALIDATOR_DIR   = path.join(configDir, 'validator')
// The stack ref this CLI tells an operator to install. xchain-node's own
// version IS the platform version, so deriving the hint here keeps it on the
// release the operator is actually holding, and it cannot rot the way a
// hardcoded ref does. It said `master` until 2026-09-01: an unpinned tracking
// install, contradicting every other instruction we give, printed at the exact
// moment a new validator is deciding what to run.
const RELEASE_REF = 'v' + require('../../../package.json').version
let KEY_FILE        = path.join(VALIDATOR_DIR, 'signing.key')
let SETTINGS_FILE   = path.join(VALIDATOR_DIR, 'validator.json')

// The ONLY file allowed in CAPS_DIR: that whole directory is bind-mounted into
// the hub container (see the header comment), so anything else added here is
// handed to the hub too.
const CAPS_BASENAME   = 'capabilities.json'
let CAPS_DIR        = path.join(VALIDATOR_DIR, 'hub-caps')
let CAPS_FILE       = path.join(CAPS_DIR, CAPS_BASENAME)

// Where installs before the hub-caps split kept the same file. Migrated on
// first use; never mounted (it is the single-file mount that broke docker cp).
let LEGACY_CAPS_FILE = path.join(VALIDATOR_DIR, CAPS_BASENAME)

// In-container mount points (see ModuleService buildAndUp). The DIRECTORY is
// what gets mounted; the file path the hub reads is unchanged from when the
// file itself was mounted, so no hub-side change is needed.
const CAPS_CONTAINER_DIR  = '/validator'
const CAPS_CONTAINER_PATH = CAPS_CONTAINER_DIR + '/' + CAPS_BASENAME

// The two coin wallets and the DOGE signer module. The signer directory is
// what the hub container mounts (read-only, at SIGNER_CONTAINER_DIR), so the
// stake WIF deliberately lives OUTSIDE it in wallets.env: the hub never needs
// the stake key, so the hub never sees it.
let WALLETS_FILE         = path.join(VALIDATOR_DIR, 'wallets.env')
let SIGNER_DIR           = path.join(VALIDATOR_DIR, 'signer')
let SIGNER_FILE          = path.join(SIGNER_DIR, 'signer.js')
let SIGNER_ENV_FILE      = path.join(SIGNER_DIR, '.env')

// The mountpoint the SDK is mounted onto, INSIDE the read-only signer mount.
// It must exist on the host before the container starts: docker mounts the
// parent first, and creating a missing mountpoint under a read-only bind mount
// fails with "make mountpoint: read-only file system", which does not degrade
// to a hub without a signer, it aborts container creation outright. Measured
// against the real hub image.
let SIGNER_MODULES_DIR   = path.join(SIGNER_DIR, 'node_modules')
const SIGNER_CONTAINER_DIR = '/XChainHub/operator-signer'
const SIGNER_CONTAINER_PATH = SIGNER_CONTAINER_DIR + '/signer.js'

// The P2P port names the federation: one host can serve both networks later,
// so the port is the declared split rather than anything the protocol enforces.
const NETWORK_BY_P2P_PORT = { 10001: 'mainnet', 10002: 'testnet' }
const P2P_PORT_BY_NETWORK = { mainnet: 10001, testnet: 10002 }

// Oracle round-numbering anchor per federation. A hub with a different value
// computes different round numbers and its submissions never line up, so the
// known federations' values are defaults here; --oracle-epoch-start overrides.
// Both values are deliberately in the PAST: an epoch in the future numbers
// every round negative and OracleRound drops peer submissions for round < 0,
// which is what cost testnet a federation-wide flag day on 2026-08-28.
// testnet: read from the live validator01-05 containers on 2026-08-29.
// mainnet: ruled by the operator board 2026-09-01 (2026-09-01T00:00:00Z).
const ORACLE_EPOCH_START_BY_NETWORK = { mainnet: 1788220800000, testnet: 1787875200000 }

// SDK network names and public encoder coin prefixes per hub network.
const COIN_NETWORKS = {
    mainnet: { stake: 'bitcoin-mainnet', doge: 'dogecoin-mainnet', stakeCoin: 'BTC',  dogeCoin: 'DOGE'  },
    testnet: { stake: 'bitcoin-testnet', doge: 'dogecoin-testnet', stakeCoin: 'TBTC', dogeCoin: 'TDOGE' },
    regtest: { stake: 'bitcoin-regtest', doge: 'dogecoin-regtest', stakeCoin: 'BTC',  dogeCoin: 'DOGE'  }
}
const PUBLIC_ENCODER_BASE = 'https://encoder.xchain.io/'

// True only for a real regular file (a directory at the same path is not one).
// Docker AUTO-CREATES a missing bind-mount source as a directory, so the legacy
// single-file mount leaves exactly that carcass behind on any host where the
// file was removed: existsSync() alone would call it a config file and migrate
// a directory over the live one.
function isRegularFile(p) {
    try { return fs.lstatSync(p).isFile() } catch { return false }
}

function configureDependencies(dependencies) {
    ;({ fs, path, configDir } = dependencies)
    VALIDATOR_DIR = path.join(configDir, 'validator')
    KEY_FILE = path.join(VALIDATOR_DIR, 'signing.key')
    SETTINGS_FILE = path.join(VALIDATOR_DIR, 'validator.json')
    CAPS_DIR = path.join(VALIDATOR_DIR, 'hub-caps')
    CAPS_FILE = path.join(CAPS_DIR, CAPS_BASENAME)
    LEGACY_CAPS_FILE = path.join(VALIDATOR_DIR, CAPS_BASENAME)
    WALLETS_FILE = path.join(VALIDATOR_DIR, 'wallets.env')
    SIGNER_DIR = path.join(VALIDATOR_DIR, 'signer')
    SIGNER_FILE = path.join(SIGNER_DIR, 'signer.js')
    SIGNER_ENV_FILE = path.join(SIGNER_DIR, '.env')
    SIGNER_MODULES_DIR = path.join(SIGNER_DIR, 'node_modules')
    Object.assign(module.exports, { VALIDATOR_DIR, RELEASE_REF, KEY_FILE, SETTINGS_FILE, CAPS_BASENAME, CAPS_DIR, CAPS_FILE, LEGACY_CAPS_FILE, CAPS_CONTAINER_DIR, CAPS_CONTAINER_PATH, WALLETS_FILE, SIGNER_DIR, SIGNER_FILE, SIGNER_ENV_FILE, SIGNER_MODULES_DIR, SIGNER_CONTAINER_DIR, SIGNER_CONTAINER_PATH, NETWORK_BY_P2P_PORT, P2P_PORT_BY_NETWORK, ORACLE_EPOCH_START_BY_NETWORK, COIN_NETWORKS, PUBLIC_ENCODER_BASE, isRegularFile })
}

module.exports = { VALIDATOR_DIR, RELEASE_REF, KEY_FILE, SETTINGS_FILE, CAPS_BASENAME, CAPS_DIR, CAPS_FILE, LEGACY_CAPS_FILE, CAPS_CONTAINER_DIR, CAPS_CONTAINER_PATH, WALLETS_FILE, SIGNER_DIR, SIGNER_FILE, SIGNER_ENV_FILE, SIGNER_MODULES_DIR, SIGNER_CONTAINER_DIR, SIGNER_CONTAINER_PATH, NETWORK_BY_P2P_PORT, P2P_PORT_BY_NETWORK, ORACLE_EPOCH_START_BY_NETWORK, COIN_NETWORKS, PUBLIC_ENCODER_BASE, isRegularFile, configureDependencies }
