/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 * XChain Node - Validator Service
 *
 * Validator-mode onboarding for the xchain-hub. `validator init` generates
 * an Ed25519 signing key and writes the validator config that install/start
 * inject into the hub container so it runs as a full validator (P2P + PBFT +
 * capability staking) instead of a standalone config oracle.
 *
 * Files (under configDir/validator/):
 *   signing.key                 64-hex Ed25519 seed (mode 0600): SIGNING_PRIVKEY_HEX
 *   validator.json              P2P + oracle settings + enabled flag + pubkey
 *   hub-caps/capabilities.json  HUB_CAPABILITY_CONFIG: MIN_STAKE thresholds +
 *                               self-test blocks
 *   wallets.env                 the two coin wallets (mode 0600): the BTC stake
 *                               wallet (funds fees, mints and holds the STAKE)
 *                               and the DOGE publisher wallet (pays for price
 *                               rounds and anchors). Generated by init, or
 *                               imported from operator-supplied WIFs.
 *   signer/signer.js + .env     the HUB_SIGNER_MODULE the hub loads to sign
 *                               DOGE publishes. Mounted read-only into the
 *                               container; the WIF stays in this directory.
 *
 * Both wallets are ordinary single-key P2PKH wallets, so an operator who wants
 * a branded (vanity) address generates the key elsewhere and imports the WIF:
 * `--import-stake-key` / `--import-doge-key` prompt for it with echo off, and
 * XCHAIN_NODE_STAKE_WIF / XCHAIN_NODE_DOGE_WIF carry it non-interactively.
 * Never as an argv value: a WIF in argv is a WIF in every process listing.
 *
 * The hub's API key is deliberately NOT one of these. A hub refuses to boot
 * without HUB_API_KEY unless keyless operation is declared, so a FRESH init
 * mints one, but it belongs to the HOST rather than to this validator identity:
 * the local indexer and the shared services authenticate to the same hub with
 * the same value. It therefore lives in the shared 0600 sidecar config/hub.local
 * alongside HUB_DB_PASS (ConfigService.ensureHubApiKey). A RE-RUN over an
 * already-initialized node only READS it (ConfigService.readHubApiKey): see
 * initValidator for why minting there breaks a keyless deployment.
 *
 * Why capabilities.json sits in its own `hub-caps/` subdirectory rather than
 * beside the other two: the hub container mounts it, and a SINGLE-FILE bind
 * mount breaks `docker cp` against that container forever. Docker's copy path
 * recreates every mount destination as a directory, so it hits the existing
 * file and aborts the whole operation with
 * "mkdirat validator/capabilities.json: file exists" - for ANY path copied,
 * not just the mounted one. Mounting a DIRECTORY instead has no such problem.
 * The directory that gets mounted must therefore contain the capability config
 * and NOTHING else: mounting `validator/` itself would put signing.key, the
 * validator's private key, inside the hub container. ensureCapabilityConfigLayout()
 * migrates pre-hub-caps installs, and assertCapsDirIsolated() refuses to build
 * the mount if anything else ever lands in that directory.
 *
 * The private key is never logged. Only the PUBLIC key is printed (operators
 * stake to it).
 ********************************************************************/

let fs = require('fs')
let childProcess = require('child_process')
let config = require('../../config')
let { WALLETS_FILE, isRegularFile } = require('./validator_paths')

// Lazy: the SDK pulls in the whole bitcoinjs stack, and every validator
// subcommand that does not touch a wallet (status) should not pay for it.
function loadSdk() {
    return require('@dankest-llc/xchain-sdk')
}

// Generate a fresh single-key wallet on the named SDK network, or import one
// from a WIF. Returns address + public key + WIF; the caller decides where the
// WIF is written and it is never printed.
function makeCoinWallet(sdkNetwork, wif) {
    const { XChainSDK } = loadSdk()
    const sdk  = new XChainSDK({ network: sdkNetwork })
    const keys = wif ? sdk.wallet.importWIF(wif) : sdk.wallet.generateKeyPair()
    return {
        address:   sdk.wallet.deriveAddress(keys.publicKey),
        pubkeyHex: keys.publicKeyHex,
        wif:       keys.wif
    }
}

// Read a secret from the CONTROLLING TERMINAL with echo off. /dev/tty rather
// than stdin, so a pasted multi-line block cannot race the prompt. Returns
// null when there is no terminal, so a non-interactive caller gets a clear
// error naming the env var instead of a hang.
function promptSecret(promptText) {
    const { execFileSync } = childProcess
    let fd
    try { fd = fs.openSync('/dev/tty', 'rs') } catch { return null }
    let echoOff = false
    try { execFileSync('stty', ['-echo'], { stdio: [fd, 'ignore', 'ignore'] }); echoOff = true } catch { /* not a tty */ }
    process.stderr.write(promptText)
    const buf = Buffer.alloc(1)
    let out = ''
    try {
        for (;;) {
            let n = 0
            try { n = fs.readSync(fd, buf, 0, 1, null) }
            catch (e) { if (e.code === 'EAGAIN') continue; throw e }
            if (n === 0) break
            const ch = buf.toString('utf8')
            if (ch === '\n' || ch === '\r') break
            if (ch === '\u0003') { out = ''; break }
            if (ch === '\u007f') { out = out.slice(0, -1); continue }
            out += ch
        }
    } finally {
        if (echoOff) { try { execFileSync('stty', ['echo'], { stdio: [fd, 'ignore', 'ignore'] }) } catch { /* best effort */ } }
        process.stderr.write('\n')
        try { fs.closeSync(fd) } catch { /* closed */ }
    }
    return out.trim()
}

// Resolve an operator-supplied WIF for one wallet: the env var first (the
// non-interactive path), then a hidden prompt. Throws when asked to import and
// neither is available, because silently generating instead would strand the
// coin the operator already funded at their own address.
function resolveImportedWif(label, envName, wantImport) {
    const fromEnv = config.IMPORTED_WIF_ENV[envName]
    if (fromEnv) return fromEnv
    if (!wantImport) return null
    const typed = promptSecret('WIF for the ' + label + ' wallet (input hidden): ')
    if (!typed) {
        throw new Error('no WIF supplied for the ' + label + ' wallet. Type it at the prompt on a terminal, ' +
            'or set ' + envName + ' in the environment (never on the command line).')
    }
    return typed
}

// Parse a KEY=VALUE sidecar into an object. Comments and blank lines skipped.
function parseEnvText(text) {
    const out = {}
    for (const line of String(text || '').split(/\r?\n/)) {
        if (!line || line.startsWith('#')) continue
        const eq = line.indexOf('=')
        if (eq <= 0) continue
        out[line.substring(0, eq).trim()] = line.substring(eq + 1).trim()
    }
    return out
}

// The wallets file, or null when this validator has none (a pre-wallets init,
// or an operator running their own signer via XCHAIN_NODE_HUB_SIGNER_DIR).
function readWallets() {
    if (!isRegularFile(WALLETS_FILE)) return null
    try { return parseEnvText(fs.readFileSync(WALLETS_FILE, 'utf8')) } catch { return null }
}

// Addresses and public keys only: what `status` prints and what the hub env
// carries. The WIFs never leave the file through this path.
function publicWalletInfo(wallets) {
    if (!wallets) return null
    return {
        network:         wallets.NETWORK || null,
        stakeAddress:    wallets.STAKE_ADDRESS || null,
        stakePubkeyHex:  wallets.STAKE_PUBKEY_HEX || null,
        dogeAddress:     wallets.DOGE_ADDRESS || null,
        dogePubkeyHex:   wallets.DOGE_PUBKEY_HEX || null
    }
}

function writeWalletsFile(network, stake, doge) {
    const body = [
        '# xchain-node validator wallets, written by `xchain-node validator init`.',
        '# Mode 0600. BACK THIS FILE UP OFFLINE: there is no recovery for a lost key.',
        '# STAKE_* is the BTC wallet that funds fees, mints XCHAIN and holds the STAKE.',
        '# DOGE_* is the wallet the hub spends from to publish price rounds and anchors.',
        'NETWORK=' + network,
        'STAKE_ADDRESS=' + stake.address,
        'STAKE_PUBKEY_HEX=' + stake.pubkeyHex,
        'STAKE_WIF_SECRET=' + stake.wif,
        'DOGE_ADDRESS=' + doge.address,
        'DOGE_PUBKEY_HEX=' + doge.pubkeyHex,
        'DOGE_WIF_SECRET=' + doge.wif,
        ''
    ].join('\n')
    fs.writeFileSync(WALLETS_FILE, body, { mode: 0o600 })
    fs.chmodSync(WALLETS_FILE, 0o600)
}

function configureDependencies(dependencies) {
    ;({ fs, childProcess, config, WALLETS_FILE, isRegularFile } = dependencies)
}

module.exports = { loadSdk, makeCoinWallet, promptSecret, resolveImportedWif, parseEnvText, readWallets, publicWalletInfo, writeWalletsFile, configureDependencies }
