/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 * XChain Node - SQL provisioning safety helpers
 *
 * MariaDB DDL used for provisioning (CREATE USER / CREATE DATABASE / GRANT)
 * cannot bind identifiers, and the docker-exec path pipes raw SQL text rather
 * than using bound parameters, so provisioning statements are assembled as
 * strings. These helpers keep that assembly injection-safe:
 *
 *   - identifiers (database names, account user names) go through a strict
 *     allowlist and never reach SQL unescaped;
 *   - the one value that may legitimately carry arbitrary bytes (an account
 *     password) is escaped as a quoted string literal at the use site.
 ********************************************************************/

'use strict'

// Database names and account user names this node provisions are, by
// construction, [A-Za-z0-9_]+ (see getModuleDatabaseName, the DB_USER config
// defaults, and getOsUserDbName's sanitizer). Gate them through this allowlist
// before concatenation so a malformed or hostile identifier fails loud instead
// of altering the statement.
const SAFE_IDENTIFIER = /^[A-Za-z0-9_]+$/

// Validate a value destined to be used as a bare/quoted MariaDB identifier.
// Returns the value unchanged when safe; throws an actionable (value-free)
// error otherwise. Never pass a secret here: the failure branch does not echo
// the value, but identifiers are not secrets and passwords must be escaped, not
// validated, so keep passwords out of this function entirely.
function assertSafeDbIdentifier(value, kind = 'identifier') {
    if (typeof value !== 'string' || !SAFE_IDENTIFIER.test(value)) {
        throw new Error('Unsafe MariaDB ' + kind + ': must match [A-Za-z0-9_]+')
    }
    return value
}

// Escape an arbitrary value into a single-quoted MariaDB string literal,
// returning the value WITH its surrounding quotes. Used for the account
// password in `IDENTIFIED BY <literal>`. Mirrors mysql_real_escape_string under
// MariaDB's default sql_mode (NO_BACKSLASH_ESCAPES off), where backslash is an
// escape character. Values generated by generatePassword() (base64url) contain
// none of these characters, so this is a no-op for the common case and only
// bites operator-supplied passwords carrying quotes/backslashes.
function escapeSqlStringLiteral(value) {
    const escaped = String(value).replace(/[\0\b\t\n\r\x1a\\'"]/g, (ch) => {
        switch (ch) {
            case '\0':   return '\\0'
            case '\b':   return '\\b'
            case '\t':   return '\\t'
            case '\n':   return '\\n'
            case '\r':   return '\\r'
            case '\x1a': return '\\Z'
            case '\\':   return '\\\\'
            case '\'':   return '\\\''
            case '"':    return '\\"'
            default:     return ch
        }
    })
    return '\'' + escaped + '\''
}

module.exports = {
    assertSafeDbIdentifier,
    escapeSqlStringLiteral
}
