#Credentials
rpcuser=__XCHAIN_NODE_RPC_USER__
rpcpassword=__XCHAIN_NODE_RPC_PASSWORD__
#allow json-rpc requests
server=1
#index all transactions so users can retrieve them with the id
txindex=1
regtest=1
#regtest can't estimate any fee because of the lack of transactions. This will be the fee rate used
fallbackfee=0.00001
maxtxfee=1.1
rpcworkqueue=128
rpcthreads=16

[regtest]
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0
rpcport=18444
rpctimeout=30
limitdescendantcount=2500
limitdescendantsize=3000
port=18443
bind=0.0.0.0:18443